import { describe, it, expect } from "vitest";
import { BlitConnection } from "../BlitConnection";
import { MockTransport } from "./mock-transport";
import type { BlitWasmModule } from "../TerminalStore";
import { S2C_FRAGMENT, FRAGMENT_FLAG_LAST, C2S_TERM_CWD } from "../types";
import {
  FEATURE_FS,
  FS_CLOSED_CLIENT_REQUEST,
  FS_CLOSED_CONNECTION_LOST,
  FS_CLOSED_ROOT_GONE,
  FS_CONTENT_FULL,
  FS_DONE_OK,
  FS_OP_MKDIR,
  FS_OP_REMOVE,
  C2S_FS_OP,
  C2S_FS_WRITE,
  FS_ENTRY_DIR,
  FS_ENTRY_FILE,
  FS_ENTRY_NO_CONTENT,
  FS_FILE_OK,
  FS_STATUS_NOT_FOUND,
  FS_SYNC_CONTENT,
  FS_SYNC_RECURSIVE,
  FS_UPDATE_RESET,
  FS_UPDATE_SYNC,
  FsMirror,
  type FsRecord,
  type FsSyncHandle,
  appendFsRecord,
  applyFsDelta,
  buildFsAckMessage,
  buildFsDoneMessage,
  buildFsFetchMessage,
  buildFsOpMessage,
  buildFsStopMessage,
  buildFsSyncMessage,
  buildFsUpdateMessage,
  buildFsWriteMessage,
  fsCompress,
  fsCompressLiteral,
  buildFsGrepMessage,
  parseFsGrepResult,
  fsGrepRecords,
  FS_GREP_CASE_SENSITIVE,
  FS_GREP_REGEX,
  FS_GREP_TRUNCATED,
  FS_GREP_FILE_IGNORED,
  FS_GREP_RECORD_FILE,
  FS_GREP_RECORD_MATCH,
  S2C_FS_GREP,
  FS_DONE_INVALID,
  C2S_FS_GREP,
  fsDecompress,
  fsRecords,
  parseFsDoneMessage,
  parseFsFileMessage,
  buildFsIndexMessage,
  parseFsIndexResult,
  C2S_FS_ACK,
  C2S_FS_INDEX,
  C2S_FS_STOP,
  C2S_FS_SYNC,
  FS_INDEX_MAX_COUNT,
  FS_DONE_CONFLICT,
  FS_DONE_NOT_FOUND,
  FS_INDEX_TRUNCATED,
  S2C_FS_INDEX,
  FS_DONE_PERMISSION,
  FS_OP_HARDLINK,
  FS_OP_MKPARENTS,
  FS_OP_NO_CAS,
  FS_OP_RENAME,
  FS_OP_SYMLINK,
  FS_WRITE_CONTENT_FULL,
  FS_WRITE_MKPARENTS,
  S2C_FS_CLOSED,
  S2C_FS_FILE,
  S2C_FS_SYNCED,
  S2C_FS_UPDATE,
} from "../fs";

function fromHex(hex: string): Uint8Array {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) {
    out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  }
  return out;
}

function toHex(bytes: Uint8Array): string {
  return [...bytes].map((b) => b.toString(16).padStart(2, "0")).join("");
}

/**
 * Byte fixtures generated by the Rust codecs in `crates/remote/src/fs.rs`
 * (see the matching `wire_fixtures` test there). Both implementations pin
 * the same bytes, so any codec drift fails on one side or the other.
 */
const FIXTURE_SYNC = "40020103001900000001000d002f746d702f7761746368206d65";
const FIXTURE_STOP = "410201";
const FIXTURE_ACK = "42020104030201";
const FIXTURE_FETCH = "43030002010b007375622f2546462e62696e";
const FIXTURE_RECORDS =
  "3700000001000500612e747874050000000000000015cd853dfe9c9717a48100008877665544332211efcdab8967452301010500000068656c6c6f2c0000000101030073756200000000000000000000000000000000ed41000000000000000000000000000000000000003400000001080b007375622f2546462e62696e0000100000000000010000000000000080810000ff00000000000000000000000000000000060000000203006f6c640b0000000303007372630300647374";
// FIXTURE_RECORDS compressed by lz4_flex (real matches, not literal-only)
// inside a full S2C_FS_UPDATE(sync_id=0x0102, update_id=7, RESET|SYNC).
const FIXTURE_UPDATE =
  "4102010700000003bc000000f2003700000001000500612e74787405000100f00e15cd853dfe9c9717a48100008877665544332211efcdab89674523010125006068656c6c6f2c3b0062010300737562370006020026ed410c000502001034300020080b3000b12f2546462e62696e0000101f001101060070000080810000ff0900080200f00a060000000203006f6c640b0000000303007372630300647374";
const FIXTURE_FILE = "4209000012000000f00366696c652d636f6e74656e742d6279746573";
const FIXTURE_SYNCED = "40020103000002002f77";

/** The records encoded by FIXTURE_RECORDS, as TS record values. */
function fixtureRecords(): FsRecord[] {
  return [
    {
      kind: "upsert",
      path: "a.txt",
      entryFlags: FS_ENTRY_FILE,
      size: 5,
      mtimeNs: 1_700_000_000_123_456_789n,
      mode: 0o100644,
      hash: 0x0123_4567_89ab_cdef_1122_3344_5566_7788n,
      content: { kind: "full", data: new TextEncoder().encode("hello") },
    },
    {
      kind: "upsert",
      path: "sub",
      entryFlags: FS_ENTRY_DIR,
      size: 0,
      mtimeNs: 0n,
      mode: 0o40755,
      hash: 0n,
      content: { kind: "none" },
    },
    {
      kind: "upsert",
      path: "sub/%FF.bin", // server-escaped non-UTF-8 name, opaque here
      entryFlags: FS_ENTRY_FILE | FS_ENTRY_NO_CONTENT,
      size: 1 << 20,
      mtimeNs: 1n,
      mode: 0o100600,
      hash: 0xffn,
      content: { kind: "none" },
    },
    { kind: "delete", path: "old" },
    { kind: "move", from: "src", to: "dst" },
  ];
}

describe("fs wire fixtures (cross-checked with Rust)", () => {
  it("C2S builders emit the pinned bytes", () => {
    expect(
      toHex(
        buildFsSyncMessage(
          0x0102,
          FS_SYNC_RECURSIVE | FS_SYNC_CONTENT,
          25,
          65536,
          "/tmp/watch me",
        ),
      ),
    ).toBe(FIXTURE_SYNC);
    expect(toHex(buildFsStopMessage(0x0102))).toBe(FIXTURE_STOP);
    expect(toHex(buildFsAckMessage(0x0102, 0x01020304))).toBe(FIXTURE_ACK);
    expect(toHex(buildFsFetchMessage(3, 0x0102, "sub/%FF.bin"))).toBe(
      FIXTURE_FETCH,
    );
    // FROM_PTY sync (docs/ide.md Decision 3): flag bit set + trailing src pty.
    expect(
      toHex(buildFsSyncMessage(7, FS_SYNC_RECURSIVE, 0, 0, "sub", 42)),
    ).toBe("400700110000000000000003007375622a00");
    // Both optional trailers, in field order: EXCLUDE then FROM_PTY
    // (docs/design/fs-watch.md "Ignoring").
    expect(
      toHex(
        buildFsSyncMessage(7, FS_SYNC_RECURSIVE, 0, 0, "sub", 42, "target"),
      ),
    ).toBe("4007009100000000000000030073756206007461726765742a00");
    // No patterns leaves the message exactly as it was before the field.
    expect(
      toHex(buildFsSyncMessage(7, FS_SYNC_RECURSIVE, 0, 0, "sub", 42, "")),
    ).toBe("400700110000000000000003007375622a00");
  });

  it("record encoder emits the pinned bytes", () => {
    const buf: number[] = [];
    for (const record of fixtureRecords()) {
      appendFsRecord(buf, record);
    }
    expect(toHex(new Uint8Array(buf))).toBe(FIXTURE_RECORDS);
  });

  it("record decoder parses the pinned bytes", () => {
    const decoded = [...fsRecords(fromHex(FIXTURE_RECORDS))];
    const expected = fixtureRecords();
    expect(decoded.length).toBe(expected.length);
    for (let i = 0; i < expected.length; i++) {
      const d = decoded[i];
      const e = expected[i];
      expect(d.kind).toBe(e.kind);
      if (d.kind === "upsert" && e.kind === "upsert") {
        expect(d.path).toBe(e.path);
        expect(d.entryFlags).toBe(e.entryFlags);
        expect(d.size).toBe(e.size);
        expect(d.mtimeNs).toBe(e.mtimeNs);
        expect(d.mode).toBe(e.mode);
        expect(d.hash).toBe(e.hash);
        expect(d.content.kind).toBe(e.content.kind);
        if (d.content.kind === "full" && e.content.kind === "full") {
          expect(toHex(d.content.data)).toBe(toHex(e.content.data));
        }
      } else {
        expect(d).toEqual(e);
      }
    }
  });

  it("applies a Rust-compressed FS_UPDATE (real LZ4 with matches)", () => {
    const mirror = new FsMirror();
    expect(mirror.applyUpdate(fromHex(FIXTURE_UPDATE))).toBe(7);
    // RESET|SYNC: the staged map swapped in.
    expect(mirror.live.size).toBe(3);
    expect(new TextDecoder().decode(mirror.live.get("a.txt")!.content!)).toBe(
      "hello",
    );
    expect(mirror.live.get("sub")!.entryFlags).toBe(FS_ENTRY_DIR);
    const escaped = mirror.live.get("sub/%FF.bin")!;
    expect(escaped.content).toBeNull();
    expect(escaped.size).toBe(1 << 20);
    expect(escaped.hash).toBe(0xffn);
  });

  it("parses a Rust-compressed FS_FILE", () => {
    const parsed = parseFsFileMessage(fromHex(FIXTURE_FILE));
    expect(parsed).not.toBeNull();
    expect(parsed!.nonce).toBe(9);
    expect(parsed!.status).toBe(FS_FILE_OK);
    expect(new TextDecoder().decode(parsed!.data)).toBe("file-content-bytes");
  });

  it("write-family builders emit the pinned bytes", () => {
    // Cross-checked with crates/remote/src/fs.rs fs_write_family_byte_fixtures.
    const base = 0x0f0e0d0c0b0a09080706050403020100n;
    expect(
      toHex(
        buildFsWriteMessage({
          nonce: 0x0102,
          syncId: 0x0304,
          flags: FS_WRITE_MKPARENTS,
          base,
          mode: 0o644,
          contentKind: FS_WRITE_CONTENT_FULL,
          path: "a/b.txt",
          content: new TextEncoder().encode("hi"),
        }),
      ),
    ).toBe(
      "440201040302000102030405060708090a0b0c0d0e0fa4010000010700612f622e74787402000000206869",
    );
    expect(
      toHex(
        buildFsOpMessage({
          nonce: 0x0102,
          syncId: 0x0304,
          op: FS_OP_RENAME,
          flags: FS_OP_MKPARENTS,
          base: 0n,
          mode: 0,
          a: "x",
          b: "y",
        }),
      ),
    ).toBe(
      "450201040303020000000000000000000000000000000000000000010078010079",
    );
    // A symlink target is a verbatim string, never a wire path — "../t"
    // rides the `a` field unescaped and unvalidated.
    expect(
      toHex(
        buildFsOpMessage({
          nonce: 0x0102,
          syncId: 0x0304,
          op: FS_OP_SYMLINK,
          flags: FS_OP_NO_CAS,
          base: 0n,
          mode: 0,
          a: "../t",
          b: "l",
        }),
      ),
    ).toBe(
      "45020104030401000000000000000000000000000000000000000004002e2e2f7401006c",
    );
    const doneHex = "4402010b000102030405060708090a0b0c0d0e0f8877665544332211";
    expect(
      toHex(
        buildFsDoneMessage(0x0102, FS_DONE_CONFLICT, base, 0x1122334455667788n),
      ),
    ).toBe(doneHex);
    expect(parseFsDoneMessage(fromHex(doneHex))).toEqual({
      nonce: 0x0102,
      status: FS_DONE_CONFLICT,
      hash: base,
      mtimeNs: 0x1122334455667788n,
    });
  });
});

function upsertRecords(path: string, content: string): Uint8Array {
  const bytes = new TextEncoder().encode(content);
  const buf: number[] = [];
  appendFsRecord(buf, {
    kind: "upsert",
    path,
    entryFlags: FS_ENTRY_FILE,
    size: bytes.length,
    mtimeNs: 42n,
    mode: 0o644,
    hash: 7n,
    content: { kind: "full", data: bytes },
  });
  return new Uint8Array(buf);
}

function upsertWithHash(
  path: string,
  content: string,
  hash: bigint,
): Uint8Array {
  const bytes = new TextEncoder().encode(content);
  const buf: number[] = [];
  appendFsRecord(buf, {
    kind: "upsert",
    path,
    entryFlags: FS_ENTRY_FILE,
    size: bytes.length,
    mtimeNs: 1n,
    mode: 0o644,
    hash,
    content: { kind: "full", data: bytes },
  });
  return new Uint8Array(buf);
}

function concat(...parts: Uint8Array[]): Uint8Array {
  const out = new Uint8Array(parts.reduce((n, p) => n + p.length, 0));
  let offset = 0;
  for (const p of parts) {
    out.set(p, offset);
    offset += p.length;
  }
  return out;
}

describe("FsMirror", () => {
  it("staged snapshot, live edits, mid-stream restage", () => {
    const mirror = new FsMirror();
    // Snapshot: RESET+SYNC with two files.
    const records = concat(
      upsertRecords("a.txt", "alpha"),
      upsertRecords("d/b.txt", "beta"),
    );
    expect(
      mirror.applyUpdate(
        buildFsUpdateMessage(1, 1, FS_UPDATE_RESET | FS_UPDATE_SYNC, records),
      ),
    ).toBe(1);
    expect(mirror.live.size).toBe(2);
    expect(new TextDecoder().decode(mirror.live.get("a.txt")!.content!)).toBe(
      "alpha",
    );

    // Live delete + move.
    const buf: number[] = [];
    appendFsRecord(buf, { kind: "delete", path: "a.txt" });
    appendFsRecord(buf, { kind: "move", from: "d", to: "e" });
    expect(
      mirror.applyUpdate(buildFsUpdateMessage(1, 2, 0, new Uint8Array(buf))),
    ).toBe(2);
    expect(mirror.live.size).toBe(1);
    expect(new TextDecoder().decode(mirror.live.get("e/b.txt")!.content!)).toBe(
      "beta",
    );

    // Mid-stream RESET without SYNC leaves live untouched…
    expect(
      mirror.applyUpdate(
        buildFsUpdateMessage(
          1,
          3,
          FS_UPDATE_RESET,
          upsertRecords("n.txt", "new"),
        ),
      ),
    ).toBe(3);
    expect(mirror.live.size).toBe(1);
    expect(mirror.live.has("e/b.txt")).toBe(true);
    // …until SYNC swaps atomically.
    expect(
      mirror.applyUpdate(
        buildFsUpdateMessage(1, 4, FS_UPDATE_SYNC, new Uint8Array(0)),
      ),
    ).toBe(4);
    expect(mirror.live.size).toBe(1);
    expect(mirror.live.has("n.txt")).toBe(true);
  });

  it("subtree prefix semantics: 'ab' is not under 'a'", () => {
    const mirror = new FsMirror();
    const records = concat(
      upsertRecords("a", "x"),
      upsertRecords("a/b", "x"),
      upsertRecords("ab", "x"),
      upsertRecords("z", "x"),
    );
    mirror.applyUpdate(
      buildFsUpdateMessage(1, 1, FS_UPDATE_RESET | FS_UPDATE_SYNC, records),
    );
    const buf: number[] = [];
    appendFsRecord(buf, { kind: "delete", path: "a" });
    mirror.applyUpdate(buildFsUpdateMessage(1, 2, 0, new Uint8Array(buf)));
    expect([...mirror.live.keys()].sort()).toEqual(["ab", "z"]);
  });

  it("delta content against the previous ack", () => {
    const mirror = new FsMirror();
    mirror.applyUpdate(
      buildFsUpdateMessage(
        1,
        1,
        FS_UPDATE_RESET | FS_UPDATE_SYNC,
        upsertRecords("f", "hello world"),
      ),
    );
    // COPY(0,6) + INSERT("blit") == "hello blit"
    const ops = new Uint8Array([0x01, 0, 6, 0x02, 4, 0x62, 0x6c, 0x69, 0x74]);
    const buf: number[] = [];
    appendFsRecord(buf, {
      kind: "upsert",
      path: "f",
      entryFlags: FS_ENTRY_FILE,
      size: 10,
      mtimeNs: 43n,
      mode: 0o644,
      hash: 8n,
      content: { kind: "delta", ops },
    });
    mirror.applyUpdate(buildFsUpdateMessage(1, 2, 0, new Uint8Array(buf)));
    expect(new TextDecoder().decode(mirror.live.get("f")!.content!)).toBe(
      "hello blit",
    );
  });

  it("metadata-only upsert keeps previous content", () => {
    const mirror = new FsMirror();
    mirror.applyUpdate(
      buildFsUpdateMessage(
        1,
        1,
        FS_UPDATE_RESET | FS_UPDATE_SYNC,
        upsertRecords("f", "keep"),
      ),
    );
    const buf: number[] = [];
    appendFsRecord(buf, {
      kind: "upsert",
      path: "f",
      entryFlags: FS_ENTRY_FILE,
      size: 4,
      mtimeNs: 99n,
      mode: 0o600,
      hash: 7n,
      content: { kind: "none" },
    });
    mirror.applyUpdate(buildFsUpdateMessage(1, 2, 0, new Uint8Array(buf)));
    const node = mirror.live.get("f")!;
    expect(node.mode).toBe(0o600);
    expect(new TextDecoder().decode(node.content!)).toBe("keep");
  });

  it("rejects an oversized declared decompression length", () => {
    // A hand-forged FS_UPDATE whose LZ4 size prefix declares 1 GiB.
    const msg = new Uint8Array(8 + 4 + 16);
    const v = new DataView(msg.buffer);
    msg[0] = S2C_FS_UPDATE;
    v.setUint16(1, 1, true);
    v.setUint32(3, 1, true);
    msg[7] = 0;
    v.setUint32(8, 1 << 30, true);
    expect(new FsMirror().applyUpdate(msg)).toBeNull();

    const file = new Uint8Array(4 + 4 + 16);
    const fv = new DataView(file.buffer);
    file[0] = S2C_FS_FILE;
    fv.setUint16(1, 7, true);
    file[3] = FS_FILE_OK;
    fv.setUint32(4, 1 << 30, true);
    expect(parseFsFileMessage(file)).toBeNull();
  });

  it("carries a multi-line match's full span and text", () => {
    const parsed = parseFsGrepResult(
      buildGrepResult(3, FS_DONE_OK, 0, "", [
        ...fileRecord(0, 1, "f.txt"),
        ...matchRecord(1, 0, 4, "alpha\nbeta", 2),
      ]),
    )!;
    expect(parsed.files[0].matches[0]).toEqual({
      line: 1,
      col: 0,
      endLine: 2,
      endCol: 4,
      text: "alpha\nbeta",
    });
  });

  it("skips unknown record kinds via record_len", () => {
    const buf: number[] = [4, 0, 0, 0, 0x7f, 1, 2, 3];
    appendFsRecord(buf, { kind: "delete", path: "x" });
    const decoded = [...fsRecords(new Uint8Array(buf))];
    expect(decoded).toEqual([{ kind: "delete", path: "x" }]);
  });
});

describe("FsMirror.apply", () => {
  it("reports liveChanged only when live actually mutates", () => {
    const mirror = new FsMirror();
    // RESET: records go to staging, live untouched.
    let r = mirror.apply(
      buildFsUpdateMessage(1, 1, FS_UPDATE_RESET, upsertRecords("a", "x")),
    )!;
    expect(r.liveChanged).toBe(false);
    expect(mirror.staged?.size).toBe(1);
    expect(mirror.live.size).toBe(0);
    // More staged records: still unchanged.
    r = mirror.apply(buildFsUpdateMessage(1, 2, 0, upsertRecords("b", "y")))!;
    expect(r.liveChanged).toBe(false);
    // The SYNC swap changes live.
    r = mirror.apply(
      buildFsUpdateMessage(1, 3, FS_UPDATE_SYNC, new Uint8Array(0)),
    )!;
    expect(r.liveChanged).toBe(true);
    expect(mirror.staged).toBeNull();
    expect(mirror.live.size).toBe(2);
    // Direct applies change live.
    r = mirror.apply(buildFsUpdateMessage(1, 4, 0, upsertRecords("c", "z")))!;
    expect(r.liveChanged).toBe(true);
    // An empty direct update changes nothing.
    r = mirror.apply(buildFsUpdateMessage(1, 5, 0, new Uint8Array(0)))!;
    expect(r.liveChanged).toBe(false);
    // Deleting a path that is not mirrored changes nothing.
    const buf: number[] = [];
    appendFsRecord(buf, { kind: "delete", path: "missing" });
    r = mirror.apply(buildFsUpdateMessage(1, 6, 0, new Uint8Array(buf)))!;
    expect(r.liveChanged).toBe(false);
    // Deleting a mirrored path does.
    const del: number[] = [];
    appendFsRecord(del, { kind: "delete", path: "c" });
    r = mirror.apply(buildFsUpdateMessage(1, 7, 0, new Uint8Array(del)))!;
    expect(r.liveChanged).toBe(true);
  });

  it("collects decoded records for the caller in one pass", () => {
    const mirror = new FsMirror();
    const collected: FsRecord[] = [];
    mirror.apply(
      buildFsUpdateMessage(
        1,
        1,
        FS_UPDATE_RESET | FS_UPDATE_SYNC,
        concat(upsertRecords("a", "x"), upsertRecords("b", "y")),
      ),
      collected,
    );
    expect(
      collected.map((r) => (r.kind === "upsert" ? r.path : r.kind)),
    ).toEqual(["a", "b"]);
  });
});

describe("fs LZ4 helpers", () => {
  it("literal-only compression round-trips", () => {
    for (const len of [0, 1, 14, 15, 16, 100, 300, 5000]) {
      const data = new Uint8Array(len);
      for (let i = 0; i < len; i++) data[i] = i & 0xff;
      const out = fsDecompress(fsCompressLiteral(data));
      expect(out).not.toBeNull();
      expect(toHex(out!)).toBe(toHex(data));
    }
  });

  it("encodes empty content as lz4_flex does (size prefix + 0x00 token)", () => {
    // A bare 4-byte size prefix is NOT a valid empty block: lz4_flex
    // rejects it (ExpectedAnotherByte) and the server drops the whole
    // message — an empty-file FS_WRITE or an LSP_BUFFER release would
    // vanish silently.
    expect(toHex(fsCompressLiteral(new Uint8Array()))).toBe("0000000000");
  });

  it("decoder block-copies disjoint matches and byte-copies overlaps", () => {
    // "abcdefgh" + match(offset 8, len 8) → the disjoint copyWithin path.
    const disjoint = new Uint8Array([
      16, 0, 0, 0, 0x84, 97, 98, 99, 100, 101, 102, 103, 104, 8, 0,
    ]);
    expect(new TextDecoder().decode(fsDecompress(disjoint)!)).toBe(
      "abcdefghabcdefgh",
    );
    // "ab" + match(offset 2, len 14) → the overlapping byte-copy path.
    const overlap = new Uint8Array([16, 0, 0, 0, 0x2a, 97, 98, 2, 0]);
    expect(new TextDecoder().decode(fsDecompress(overlap)!)).toBe(
      "abababababababab",
    );
  });

  it("applyFsDelta handles multi-byte LEB128 and rejects junk", () => {
    const base = new Uint8Array(300);
    for (let i = 0; i < 300; i++) base[i] = i & 0xff;
    // COPY(offset=200 → 0xC8 0x01, len=100)
    const ops = new Uint8Array([0x01, 0xc8, 0x01, 100]);
    const out = applyFsDelta(base, ops)!;
    expect(toHex(out)).toBe(toHex(base.subarray(200, 300)));
    // COPY out of range.
    expect(
      applyFsDelta(base, new Uint8Array([0x01, 0xc8, 0x02, 100])),
    ).toBeNull();
    // Unknown op.
    expect(applyFsDelta(base, new Uint8Array([0x03]))).toBeNull();
    // Truncated INSERT.
    expect(applyFsDelta(base, new Uint8Array([0x02, 9, 1]))).toBeNull();
  });
});

/**
 * Decode one framed LZ4 payload while asserting the standard block end
 * rules that lz4_flex and the reference decoder assume: the last sequence
 * is literal-only, matches never start within the last 12 bytes, and the
 * last 5 bytes are literals.
 */
function decodeAssertingBlockRules(payload: Uint8Array): Uint8Array {
  const v = new DataView(
    payload.buffer,
    payload.byteOffset,
    payload.byteLength,
  );
  const outLen = v.getUint32(0, true);
  const src = payload.subarray(4);
  const out = new Uint8Array(outLen);
  let si = 0;
  let di = 0;
  if (outLen === 0) {
    expect(src.length).toBeLessThanOrEqual(1);
    return out;
  }
  while (si < src.length) {
    const token = src[si++];
    let litLen = token >> 4;
    if (litLen === 15) {
      let b: number;
      do {
        b = src[si++];
        litLen += b;
      } while (b === 255);
    }
    out.set(src.subarray(si, si + litLen), di);
    si += litLen;
    di += litLen;
    if (si >= src.length) break; // final sequence: literals only
    expect(di).toBeLessThanOrEqual(outLen - 12); // match start rule
    const offset = src[si] | (src[si + 1] << 8);
    si += 2;
    expect(offset).toBeGreaterThan(0);
    expect(offset).toBeLessThanOrEqual(di);
    let matchLen = (token & 0x0f) + 4;
    if ((token & 0x0f) === 15) {
      let b: number;
      do {
        b = src[si++];
        matchLen += b;
      } while (b === 255);
    }
    expect(di + matchLen).toBeLessThanOrEqual(outLen - 5); // trailing literals rule
    let mi = di - offset;
    for (let i = 0; i < matchLen; i++) out[di++] = out[mi++];
  }
  expect(di).toBe(outLen);
  return out;
}

/** Deterministic byte stream (xorshift32) for incompressible fixtures. */
function randomBytes(len: number, seed = 0x9e3779b9): Uint8Array {
  const out = new Uint8Array(len);
  let s = seed >>> 0;
  for (let i = 0; i < len; i++) {
    s ^= s << 13;
    s >>>= 0;
    s ^= s >>> 17;
    s ^= s << 5;
    s >>>= 0;
    out[i] = s & 0xff;
  }
  return out;
}

describe("fsCompress (real LZ4 block encoder)", () => {
  const enc = (s: string) => new TextEncoder().encode(s);
  const cases: Array<[string, Uint8Array]> = [
    ["empty", new Uint8Array(0)],
    ["tiny", enc("hello!")],
    ["twelve bytes (below the match floor)", enc("abcabcabcabc")],
    ["thirteen bytes", enc("abcabcabcabca")],
    ["ends deep in a match", concat(enc("prefix-"), new Uint8Array(200))],
    [
      "single-byte run (overlapping match + length extension)",
      new Uint8Array(1000).fill(0x61),
    ],
    ["repetitive", enc("abcd".repeat(4096))],
    [
      "long literal head then matches",
      concat(randomBytes(300), enc("xyzw".repeat(128))),
    ],
    ["incompressible random", randomBytes(8192)],
    [
      "text-like",
      enc("All work and no play makes blit a dull tool. ".repeat(64)),
    ],
  ];

  it("round-trips through the production decoder", () => {
    for (const [name, data] of cases) {
      const out = fsDecompress(fsCompress(data));
      expect(out, name).not.toBeNull();
      expect(toHex(out!), name).toBe(toHex(data));
    }
  });

  it("emits standard blocks honoring the end-of-block rules", () => {
    for (const [name, data] of cases) {
      expect(toHex(decodeAssertingBlockRules(fsCompress(data))), name).toBe(
        toHex(data),
      );
    }
  });

  it("actually compresses repetitive input", () => {
    const data = enc("abcd".repeat(4096));
    expect(fsCompress(data).length).toBeLessThan(data.length / 8);
    const run = new Uint8Array(1000).fill(0x61);
    expect(fsCompress(run).length).toBeLessThan(32);
  });

  it("never exceeds the literal-only encoding", () => {
    for (const [name, data] of cases) {
      expect(fsCompress(data).length, name).toBeLessThanOrEqual(
        fsCompressLiteral(data).length,
      );
    }
  });

  it("falls back to the literal-only block for tiny inputs", () => {
    for (const len of [0, 1, 5, 12]) {
      expect(toHex(fsCompress(randomBytes(len)))).toBe(
        toHex(fsCompressLiteral(randomBytes(len))),
      );
    }
  });

  it("round-trips every length across the block-rule thresholds", () => {
    for (let len = 0; len <= 80; len++) {
      // Half-repetitive so lengths just over 13 can produce matches whose
      // end collides with the trailing-literals rule.
      const data = new Uint8Array(len);
      for (let i = 0; i < len; i++) data[i] = i < len / 2 ? i & 0xff : 0x61;
      const out = decodeAssertingBlockRules(fsCompress(data));
      expect(toHex(out), `len ${len}`).toBe(toHex(data));
    }
  });
});

// -- Connection-level flow ---------------------------------------------------

class FakeTerminal {
  constructor(_r: number, _c: number, _pw: number, _ph: number) {}
  set_font_family(_f: string) {}
  set_font_size(_s: number) {}
  set_default_colors(..._a: number[]) {}
  set_ansi_color(..._a: number[]) {}
  feed_compressed(_d: Uint8Array) {}
  invalidate_render_cache() {}
  title() {
    return "";
  }
  free() {}
}

const wasm = { Terminal: FakeTerminal } as unknown as BlitWasmModule;

function fsReadyConnection(): {
  conn: BlitConnection;
  transport: MockTransport;
} {
  const transport = new MockTransport();
  const conn = new BlitConnection({
    id: "test",
    transport,
    wasm,
    autoConnect: false,
  });
  transport.pushHello(1, FEATURE_FS);
  transport.pushReady();
  return { conn, transport };
}

function pushSynced(
  transport: MockTransport,
  nonce: number,
  syncId: number,
  status: number,
  detail: string,
) {
  const detailBytes = new TextEncoder().encode(detail);
  const msg = new Uint8Array(8 + detailBytes.length);
  const v = new DataView(msg.buffer);
  msg[0] = S2C_FS_SYNCED;
  v.setUint16(1, nonce, true);
  v.setUint16(3, syncId, true);
  msg[5] = status;
  v.setUint16(6, detailBytes.length, true);
  msg.set(detailBytes, 8);
  transport.push(msg);
}

/** Run pending timers: consumer callbacks held back until the opener holds
 *  its handle are released on a task of their own. */
const flushTimers = () => new Promise((resolve) => setTimeout(resolve, 0));

describe("BlitConnection.syncFs", () => {
  it("full flow: sync, snapshot, records, ack, fetch, close", async () => {
    const { conn, transport } = fsReadyConnection();
    expect(conn.getSnapshot().supportsFsSync).toBe(true);

    const seen: FsRecord[] = [];
    let syncs = 0;
    let closedReason: number | null = null;
    const handlePromise = conn.syncFs("/watched", {
      content: true,
      onRecord: (r) => seen.push(r),
      onSync: () => syncs++,
      onClosed: (reason) => (closedReason = reason),
    });

    // The C2S_FS_SYNC went out; answer it.
    const syncMsg = transport.sent.find((m) => m[0] === C2S_FS_SYNC)!;
    expect(syncMsg).toBeDefined();
    const nonce = syncMsg[1] | (syncMsg[2] << 8);
    pushSynced(transport, nonce, 5, 0, "/watched");
    const handle = await handlePromise;
    // The open's callbacks are held until the opener holds its handle;
    // let that task run so the pushes below deliver inline.
    await flushTimers();
    expect(handle.syncId).toBe(5);
    expect(handle.root).toBe("/watched");

    // Snapshot in two updates: RESET, then SYNC.
    transport.push(
      buildFsUpdateMessage(5, 1, FS_UPDATE_RESET, upsertRecords("a", "one")),
    );
    // Staging active: live is still empty.
    expect(handle.live.size).toBe(0);
    transport.push(
      buildFsUpdateMessage(5, 2, FS_UPDATE_SYNC, upsertRecords("b", "two")),
    );
    expect(syncs).toBe(1);
    expect([...handle.live.keys()].sort()).toEqual(["a", "b"]);
    expect(seen.length).toBe(2);

    // Both updates were acked cumulatively as they arrived.
    const acks = transport.sent.filter((m) => m[0] === C2S_FS_ACK);
    expect(acks.length).toBe(2);
    const last = acks[acks.length - 1];
    expect(last[1] | (last[2] << 8)).toBe(5);
    expect(new DataView(last.buffer, 3, 4).getUint32(0, true)).toBe(2);

    // Fetch.
    const dataPromise = handle.fetch("a");
    const fetchMsg = transport.sent.filter((m) => m[0] === 0x43).pop()!;
    const fetchNonce = fetchMsg[1] | (fetchMsg[2] << 8);
    const payload = fsCompressLiteral(new TextEncoder().encode("bytes"));
    const fileMsg = new Uint8Array(4 + payload.length);
    fileMsg[0] = S2C_FS_FILE;
    fileMsg[1] = fetchNonce & 0xff;
    fileMsg[2] = (fetchNonce >> 8) & 0xff;
    fileMsg[3] = FS_FILE_OK;
    fileMsg.set(payload, 4);
    transport.push(fileMsg);
    expect(new TextDecoder().decode(await dataPromise)).toBe("bytes");

    // Server closes the sync.
    transport.push(new Uint8Array([S2C_FS_CLOSED, 5, 0, FS_CLOSED_ROOT_GONE]));
    expect(closedReason).toBe(FS_CLOSED_ROOT_GONE);

    conn.dispose();
  });

  it("reassembles a fragmented FS_UPDATE", async () => {
    const { conn, transport } = fsReadyConnection();
    const handlePromise = conn.syncFs("/w");
    const syncMsg = transport.sent.find((m) => m[0] === C2S_FS_SYNC)!;
    pushSynced(transport, syncMsg[1] | (syncMsg[2] << 8), 1, 0, "/w");
    const handle = await handlePromise;

    const update = buildFsUpdateMessage(
      1,
      1,
      FS_UPDATE_RESET | FS_UPDATE_SYNC,
      upsertRecords("frag.txt", "reassembled"),
    );
    const mid = Math.floor(update.length / 2);
    transport.push(
      concat(new Uint8Array([S2C_FRAGMENT, 0]), update.subarray(0, mid)),
    );
    expect(handle.live.size).toBe(0);
    transport.push(
      concat(
        new Uint8Array([S2C_FRAGMENT, FRAGMENT_FLAG_LAST]),
        update.subarray(mid),
      ),
    );
    expect(
      new TextDecoder().decode(handle.live.get("frag.txt")!.content!),
    ).toBe("reassembled");
    conn.dispose();
  });

  it("stages without waking subscribers until the SYNC swap", async () => {
    const { conn, transport } = fsReadyConnection();
    let updates = 0;
    let resets = 0;
    let syncs = 0;
    const seen: string[] = [];
    const handlePromise = conn.syncFs("/w", {
      content: true,
      onUpdate: () => updates++,
      onReset: () => resets++,
      onSync: () => syncs++,
      onRecord: (r) => {
        if (r.kind === "upsert") seen.push(r.path);
      },
    });
    const syncMsg = transport.sent.find((m) => m[0] === C2S_FS_SYNC)!;
    pushSynced(transport, syncMsg[1] | (syncMsg[2] << 8), 9, 0, "/w");
    const handle = await handlePromise;
    await flushTimers();
    let notified = 0;
    handle.subscribe(() => notified++);
    const rev0 = handle.revision;

    // Staged records: callbacks see them, subscribers stay asleep.
    transport.push(
      buildFsUpdateMessage(9, 1, FS_UPDATE_RESET, upsertRecords("a", "one")),
    );
    transport.push(buildFsUpdateMessage(9, 2, 0, upsertRecords("b", "two")));
    expect(resets).toBe(1);
    expect(seen).toEqual(["a", "b"]);
    expect(updates).toBe(0);
    expect(notified).toBe(0);
    expect(handle.revision).toBe(rev0);
    // Both staged updates were still acknowledged.
    expect(transport.sent.filter((m) => m[0] === C2S_FS_ACK)).toHaveLength(2);

    // The SYNC swap wakes subscribers exactly once.
    transport.push(
      buildFsUpdateMessage(9, 3, FS_UPDATE_SYNC, new Uint8Array(0)),
    );
    expect(syncs).toBe(1);
    expect(updates).toBe(1);
    expect(notified).toBe(1);
    expect(handle.revision).toBe(rev0 + 1);

    // A live (direct) update wakes them again.
    transport.push(buildFsUpdateMessage(9, 4, 0, upsertRecords("c", "three")));
    expect(updates).toBe(2);
    expect(notified).toBe(2);
    conn.dispose();
  });

  it("rejects a failed sync with the server detail", async () => {
    const { conn, transport } = fsReadyConnection();
    const handlePromise = conn.syncFs("/missing");
    const syncMsg = transport.sent.find((m) => m[0] === C2S_FS_SYNC)!;
    pushSynced(
      transport,
      syncMsg[1] | (syncMsg[2] << 8),
      0xffff,
      FS_STATUS_NOT_FOUND,
      "no such directory",
    );
    await expect(handlePromise).rejects.toThrow(/not found: no such directory/);
    conn.dispose();
  });

  it("closes live syncs when the server session restarts", async () => {
    const { conn, transport } = fsReadyConnection();
    let closedReason: number | null = null;
    const handlePromise = conn.syncFs("/w", {
      onClosed: (reason) => (closedReason = reason),
    });
    const syncMsg = transport.sent.find((m) => m[0] === C2S_FS_SYNC)!;
    pushSynced(transport, syncMsg[1] | (syncMsg[2] << 8), 2, 0, "/w");
    await handlePromise;
    await flushTimers();
    transport.pushHello(1, FEATURE_FS);
    expect(closedReason).toBe(FS_CLOSED_CONNECTION_LOST);
    conn.dispose();
  });

  it("refuses syncFs without the feature bit", async () => {
    const transport = new MockTransport();
    const conn = new BlitConnection({
      id: "test",
      transport,
      wasm,
      autoConnect: false,
    });
    transport.pushHello(1, 0);
    transport.pushReady();
    expect(conn.getSnapshot().supportsFsSync).toBe(false);
    await expect(conn.syncFs("/w")).rejects.toThrow(/does not support/);
    conn.dispose();
  });
});

describe("BlitConnection.syncFs open contract", () => {
  // A single-file sync is one record, so the server's accept echo and the
  // coherent snapshot go out back to back and reach the client in one
  // chunk; every batched transport (webtransport, mux, unix) dispatches a
  // chunk's frames in one synchronous loop, so nothing flushes microtasks
  // in between.
  function pushAcceptAndSnapshotInOneChunk(
    transport: MockTransport,
    syncId: number,
    root: string,
    records: Uint8Array,
  ) {
    const syncMsg = transport.sent.find((m) => m[0] === C2S_FS_SYNC)!;
    pushSynced(transport, syncMsg[1] | (syncMsg[2] << 8), syncId, 0, root);
    transport.push(
      buildFsUpdateMessage(
        syncId,
        1,
        FS_UPDATE_RESET | FS_UPDATE_SYNC,
        records,
      ),
    );
  }

  it("holds a fresh open's callbacks until the opener holds its handle", async () => {
    const { conn, transport } = fsReadyConnection();
    // The editor's open pattern (js/ui/src/ide/BlitEditor.tsx): the handle
    // is stored by the promise continuation, and onSync — "the snapshot is
    // coherent" — is where a still-absent file is declared missing.
    let opened: FsSyncHandle | null = null;
    let verdict: string | null = null;
    const opening = conn
      .syncFs("/w/.envrc", {
        content: true,
        single: true,
        onSync: () => {
          verdict = opened?.live.get("") ? "loaded" : "not-found";
        },
      })
      .then((h) => {
        opened = h;
      });
    pushAcceptAndSnapshotInOneChunk(
      transport,
      5,
      "/w/.envrc",
      upsertRecords("", "export FOO=1"),
    );
    await opening;
    await flushTimers();
    expect(verdict).toBe("loaded");
    conn.dispose();
  });

  it("holds a joiner's callbacks until it holds its handle", async () => {
    const { conn, transport } = fsReadyConnection();
    const p1 = conn.syncFs("/w", { content: true });
    pushAcceptAndSnapshotInOneChunk(
      transport,
      6,
      "/w",
      upsertRecords("a", "one"),
    );
    await p1;
    await flushTimers();

    // A joiner resolves off the mirror with no round trip, so its window is
    // narrower — but a frame handled before its continuation runs (an open
    // from inside another consumer's callback) hits the same trap.
    let opened: FsSyncHandle | null = null;
    let sawHandle: boolean | null = null;
    let syncs = 0;
    const seen: string[] = [];
    const joining = conn
      .syncFs("/w", {
        content: true,
        onSync: () => {
          syncs++;
          sawHandle ??= opened !== null;
        },
        onRecord: (r) => {
          if (r.kind === "upsert") seen.push(r.path);
        },
      })
      .then((h) => {
        opened = h;
      });
    transport.push(
      buildFsUpdateMessage(6, 2, FS_UPDATE_SYNC, upsertRecords("b", "two")),
    );
    await joining;
    await flushTimers();
    // One coherence signal, delivered with the handle in hand, and the
    // replay covers the update that landed while the joiner was opening.
    expect(sawHandle).toBe(true);
    expect(syncs).toBe(1);
    expect(seen.sort()).toEqual(["a", "b"]);
    conn.dispose();
  });

  it("releases a close held behind the snapshot, in order", async () => {
    const { conn, transport } = fsReadyConnection();
    const events: string[] = [];
    let opened: FsSyncHandle | null = null;
    const opening = conn
      .syncFs("/w", {
        content: true,
        onSync: () => events.push(opened ? "sync" : "sync-without-handle"),
        onClosed: (r) => events.push(`closed:${r}`),
      })
      .then((h) => {
        opened = h;
      });
    pushAcceptAndSnapshotInOneChunk(
      transport,
      7,
      "/w",
      upsertRecords("a", "one"),
    );
    // A close riding the same chunk: not reproducible from the mirror, so it
    // is always delivered — behind the snapshot it followed on the wire.
    transport.push(new Uint8Array([S2C_FS_CLOSED, 7, 0, FS_CLOSED_ROOT_GONE]));
    await opening;
    await flushTimers();
    expect(events).toEqual(["sync", `closed:${FS_CLOSED_ROOT_GONE}`]);
    conn.dispose();
  });

  it("gives a consumer that stopped before the handoff only its close", async () => {
    const { conn, transport } = fsReadyConnection();
    const first: string[] = [];
    const second: string[] = [];
    const p1 = conn.syncFs("/w", {
      content: true,
      onSync: () => first.push("sync"),
      onClosed: (r) => first.push(`closed:${r}`),
    });
    const p2 = conn.syncFs("/w", {
      content: true,
      onSync: () => second.push("sync"),
      onClosed: (r) => second.push(`closed:${r}`),
    });
    pushAcceptAndSnapshotInOneChunk(
      transport,
      8,
      "/w",
      upsertRecords("a", "one"),
    );
    const h1 = await p1;
    await p2;
    h1.stop();
    await flushTimers();
    // Nothing it never saw is owed to a stopped consumer; the survivor's
    // snapshot is untouched.
    expect(first).toEqual([`closed:${FS_CLOSED_CLIENT_REQUEST}`]);
    expect(second).toEqual(["sync"]);
    conn.dispose();
  });
});

describe("BlitConnection.syncFs coalescing", () => {
  it("shares one wire sync between wire-identical opens", async () => {
    const { conn, transport } = fsReadyConnection();
    let closed1: number | null = null;
    let closed2: number | null = null;
    let updates2 = 0;
    const p1 = conn.syncFs("/w", {
      content: true,
      onClosed: (r) => (closed1 = r),
    });
    const p2 = conn.syncFs("/w", {
      content: true,
      onClosed: (r) => (closed2 = r),
      onUpdate: () => updates2++,
    });
    const syncMsgs = transport.sent.filter((m) => m[0] === C2S_FS_SYNC);
    expect(syncMsgs).toHaveLength(1);
    pushSynced(transport, syncMsgs[0][1] | (syncMsgs[0][2] << 8), 5, 0, "/w");
    const h1 = await p1;
    const h2 = await p2;
    await flushTimers();
    expect(h1.syncId).toBe(5);
    expect(h2.syncId).toBe(5);

    transport.push(
      buildFsUpdateMessage(
        5,
        1,
        FS_UPDATE_RESET | FS_UPDATE_SYNC,
        upsertRecords("a", "one"),
      ),
    );
    // One mirror serves both handles; one ack per update, not per consumer.
    expect(h1.live).toBe(h2.live);
    expect(updates2).toBe(1);
    expect(transport.sent.filter((m) => m[0] === C2S_FS_ACK)).toHaveLength(1);

    // First stop: the wire sync stays; the close is confirmed locally.
    h1.stop();
    expect(transport.sent.filter((m) => m[0] === C2S_FS_STOP)).toHaveLength(0);
    await flushTimers();
    expect(closed1).toBe(FS_CLOSED_CLIENT_REQUEST);
    expect(closed2).toBeNull();

    // The survivor keeps receiving updates.
    transport.push(buildFsUpdateMessage(5, 2, 0, upsertRecords("b", "two")));
    expect(updates2).toBe(2);

    // Last stop releases the wire sync; the server confirms the close.
    h2.stop();
    expect(transport.sent.filter((m) => m[0] === C2S_FS_STOP)).toHaveLength(1);
    transport.push(
      new Uint8Array([S2C_FS_CLOSED, 5, 0, FS_CLOSED_CLIENT_REQUEST]),
    );
    expect(closed2).toBe(FS_CLOSED_CLIENT_REQUEST);
    conn.dispose();
  });

  it("opens distinct wire syncs for distinct paths or options", async () => {
    const { conn, transport } = fsReadyConnection();
    const pending = [
      conn.syncFs("/w", { content: true }),
      conn.syncFs("/w", {}),
      conn.syncFs("/w", { content: true, inlineMax: 4096 }),
      conn.syncFs("/x", { content: true }),
    ];
    pending.forEach((p) => void p.catch(() => {}));
    expect(transport.sent.filter((m) => m[0] === C2S_FS_SYNC)).toHaveLength(4);
    conn.dispose();
  });

  it("replays the coherent snapshot to a late joiner", async () => {
    const { conn, transport } = fsReadyConnection();
    const p1 = conn.syncFs("/w", { content: true });
    const syncMsg = transport.sent.find((m) => m[0] === C2S_FS_SYNC)!;
    pushSynced(transport, syncMsg[1] | (syncMsg[2] << 8), 6, 0, "/w");
    await p1;
    transport.push(
      buildFsUpdateMessage(
        6,
        1,
        FS_UPDATE_RESET | FS_UPDATE_SYNC,
        concat(upsertRecords("a", "one"), upsertRecords("b", "two")),
      ),
    );

    const seen: string[] = [];
    let resets = 0;
    let syncs = 0;
    let updates = 0;
    let notified = 0;
    const h2 = await conn.syncFs("/w", {
      content: true,
      onReset: () => resets++,
      onSync: () => syncs++,
      onUpdate: () => updates++,
      onRecord: (r) => {
        if (r.kind === "upsert") seen.push(r.path);
      },
    });
    h2.subscribe(() => notified++);
    // No second wire sync went out, and the live map is already coherent.
    expect(transport.sent.filter((m) => m[0] === C2S_FS_SYNC)).toHaveLength(1);
    expect(h2.live.size).toBe(2);
    // The replay lands on a later task, after the caller holds the handle.
    expect(resets).toBe(0);
    await flushTimers();
    expect(resets).toBe(1);
    expect(seen.sort()).toEqual(["a", "b"]);
    expect(syncs).toBe(1);
    expect(updates).toBe(1);
    expect(notified).toBe(1);
    conn.dispose();
  });

  it("mid-restage joiner replays staging and finishes with the wire SYNC", async () => {
    const { conn, transport } = fsReadyConnection();
    const p1 = conn.syncFs("/w", { content: true });
    const syncMsg = transport.sent.find((m) => m[0] === C2S_FS_SYNC)!;
    pushSynced(transport, syncMsg[1] | (syncMsg[2] << 8), 8, 0, "/w");
    await p1;
    // First snapshot is coherent, then a restage begins without SYNCing.
    transport.push(
      buildFsUpdateMessage(
        8,
        1,
        FS_UPDATE_RESET | FS_UPDATE_SYNC,
        upsertRecords("a", "one"),
      ),
    );
    transport.push(
      buildFsUpdateMessage(8, 2, FS_UPDATE_RESET, upsertRecords("b", "two")),
    );

    const seen: string[] = [];
    let resets = 0;
    let syncs = 0;
    let updates = 0;
    await conn.syncFs("/w", {
      content: true,
      onReset: () => resets++,
      onSync: () => syncs++,
      onUpdate: () => updates++,
      onRecord: (r) => {
        if (r.kind === "upsert") seen.push(r.path);
      },
    });
    await flushTimers();
    // The joiner got the staging map replayed, but no coherence signal yet.
    expect(resets).toBe(1);
    expect(seen).toEqual(["b"]);
    expect(syncs).toBe(0);
    expect(updates).toBe(0);
    // The wire SYNC completes the restage for everyone.
    transport.push(
      buildFsUpdateMessage(8, 3, FS_UPDATE_SYNC, new Uint8Array(0)),
    );
    expect(syncs).toBe(1);
    expect(updates).toBe(1);
    conn.dispose();
  });
});

describe("BlitConnection.sessionCwd", () => {
  it("caps in-flight cwd requests at 8", async () => {
    const { conn, transport } = fsReadyConnection();
    transport.pushList([{ ptyId: 1, tag: "t" }]);
    const sessionId = conn.getSnapshot().sessions[0].id;
    const pending = Array.from({ length: 8 }, () => conn.sessionCwd(sessionId));
    pending.forEach((p) => void p.catch(() => {}));
    expect(transport.sent.filter((m) => m[0] === C2S_TERM_CWD)).toHaveLength(8);
    // The 9th resolves to the documented can't-read result without a send.
    await expect(conn.sessionCwd(sessionId)).resolves.toBe("");
    expect(transport.sent.filter((m) => m[0] === C2S_TERM_CWD)).toHaveLength(8);
    conn.dispose();
  });
});

describe("BlitConnection writes", () => {
  async function writeReadyHandle() {
    const transport = new MockTransport();
    const conn = new BlitConnection({
      id: "test",
      transport,
      wasm,
      autoConnect: false,
    });
    transport.pushHello(1, FEATURE_FS);
    transport.pushReady();
    const handlePromise = conn.syncFs("/w");
    const syncMsg = transport.sent.find((m) => m[0] === C2S_FS_SYNC)!;
    pushSynced(transport, syncMsg[1] | (syncMsg[2] << 8), 7, 0, "/w");
    const handle = await handlePromise;
    await flushTimers();
    return { conn, transport, handle };
  }

  it("writeFile resolves with the hash and records lastWrittenHash", async () => {
    const { conn, transport, handle } = await writeReadyHandle();
    const p = handle.writeFile("a.txt", new TextEncoder().encode("hi"), {
      create: true,
    });
    const writeMsg = transport.sent.find((m) => m[0] === C2S_FS_WRITE)!;
    expect(writeMsg).toBeDefined();
    const nonce = writeMsg[1] | (writeMsg[2] << 8);
    transport.push(buildFsDoneMessage(nonce, FS_DONE_OK, 0xabcdn, 123n));
    const res = await p;
    expect(res.hash).toBe(0xabcdn);
    expect(res.mtimeNs).toBe(123n);
    // Recorded for self-echo suppression.
    expect(handle.lastWrittenHash("a.txt")).toBe(0xabcdn);
    conn.dispose();
  });

  it("writeFile rejects with FsConflictError carrying the disk hash", async () => {
    const { conn, transport, handle } = await writeReadyHandle();
    const p = handle.writeFile("a.txt", new Uint8Array(), { ifHash: 1n });
    const writeMsg = transport.sent.find((m) => m[0] === C2S_FS_WRITE)!;
    const nonce = writeMsg[1] | (writeMsg[2] << 8);
    transport.push(buildFsDoneMessage(nonce, FS_DONE_CONFLICT, 0x999n, 0n));
    await expect(p).rejects.toMatchObject({
      name: "FsConflictError",
      hash: 0x999n,
    });
    // A conflict must not record a lastWrittenHash.
    expect(handle.lastWrittenHash("a.txt")).toBeUndefined();
    conn.dispose();
  });

  it("mkdir/remove/rename emit FS_OP with the right selector and flags", async () => {
    const { conn, transport, handle } = await writeReadyHandle();
    // Fire-and-forget: no FS_DONE is mocked, so these stay pending and are
    // rejected by dispose() below — handle the rejection so it isn't unhandled.
    const pending = [
      handle.mkdir("d", { createParents: true, mode: 0o700 }),
      handle.remove("d"),
      handle.rename("d", "e"),
    ];
    pending.forEach((p) => void p.catch(() => {}));
    const ops = transport.sent.filter((m) => m[0] === C2S_FS_OP);
    expect(ops.map((m) => m[5])).toEqual([
      FS_OP_MKDIR,
      FS_OP_REMOVE,
      FS_OP_RENAME,
    ]);
    // mkdir carried MKPARENTS in its flags byte.
    expect(ops[0][6] & FS_OP_MKPARENTS).toBe(FS_OP_MKPARENTS);
    conn.dispose();
  });

  it("symlink/hardlink emit FS_OP and record the returned hash", async () => {
    const { conn, transport, handle } = await writeReadyHandle();
    const p = handle.symlink("../elsewhere/t", "ln");
    const q = handle.hardlink("src.txt", "ln2", { force: true });
    void q.catch(() => {});
    const ops = transport.sent.filter((m) => m[0] === C2S_FS_OP);
    expect(ops.map((m) => m[5])).toEqual([FS_OP_SYMLINK, FS_OP_HARDLINK]);
    // Default is create-exclusive (no NO_CAS); force sets it.
    expect(ops[0][6] & FS_OP_NO_CAS).toBe(0);
    expect(ops[1][6] & FS_OP_NO_CAS).toBe(FS_OP_NO_CAS);
    const nonce = ops[0][1] | (ops[0][2] << 8);
    transport.push(buildFsDoneMessage(nonce, FS_DONE_OK, 0x77n, 1n));
    await p;
    // Recorded for self-echo suppression, keyed by the link path.
    expect(handle.lastWrittenHash("ln")).toBe(0x77n);
    conn.dispose();
  });

  it("drops the lastWritten entry once its echo upsert is observed", async () => {
    const { conn, transport } = fsReadyConnection();
    const during: Array<bigint | undefined> = [];
    let handle: FsSyncHandle | undefined;
    const handlePromise = conn.syncFs("/w", {
      content: true,
      onRecord: () => during.push(handle?.lastWrittenHash("a.txt")),
    });
    const syncMsg = transport.sent.find((m) => m[0] === C2S_FS_SYNC)!;
    pushSynced(transport, syncMsg[1] | (syncMsg[2] << 8), 7, 0, "/w");
    handle = await handlePromise;
    await flushTimers();

    const writePromise = handle.writeFile(
      "a.txt",
      new TextEncoder().encode("hi"),
    );
    const writeMsg = transport.sent.find((m) => m[0] === C2S_FS_WRITE)!;
    const nonce = writeMsg[1] | (writeMsg[2] << 8);
    transport.push(buildFsDoneMessage(nonce, FS_DONE_OK, 0xabcdn, 1n));
    await writePromise;
    expect(handle.lastWrittenHash("a.txt")).toBe(0xabcdn);

    // A non-matching upsert keeps the entry — the echo is still coming.
    transport.push(
      buildFsUpdateMessage(7, 1, 0, upsertWithHash("a.txt", "other", 0x1n)),
    );
    expect(handle.lastWrittenHash("a.txt")).toBe(0xabcdn);

    // The echo: still visible inside callbacks, consumed afterwards.
    transport.push(
      buildFsUpdateMessage(7, 2, 0, upsertWithHash("a.txt", "hi", 0xabcdn)),
    );
    expect(during[during.length - 1]).toBe(0xabcdn);
    expect(handle.lastWrittenHash("a.txt")).toBeUndefined();
    conn.dispose();
  });

  it("scopes lastWritten to the writing handle, not the shared sync", async () => {
    const { conn, transport } = fsReadyConnection();
    const writerPromise = conn.syncFs("/w", { content: true });
    const syncMsg = transport.sent.find((m) => m[0] === C2S_FS_SYNC)!;
    pushSynced(transport, syncMsg[1] | (syncMsg[2] << 8), 7, 0, "/w");
    const writer = await writerPromise;
    await flushTimers();

    // Wire-identical second open: joins the same share, no second sync.
    const seen: Array<{ hash: bigint; suppressed: boolean }> = [];
    let reader: FsSyncHandle | undefined;
    const readerPromise = conn.syncFs("/w", {
      content: true,
      onRecord: (r) => {
        if (r.kind === "upsert")
          seen.push({
            hash: r.hash,
            suppressed: reader?.lastWrittenHash(r.path) === r.hash,
          });
      },
    });
    reader = await readerPromise;
    await flushTimers();
    expect(transport.sent.filter((m) => m[0] === C2S_FS_SYNC)).toHaveLength(1);

    const writePromise = writer.writeFile(
      "a.txt",
      new TextEncoder().encode("hi"),
    );
    const writeMsg = transport.sent.find((m) => m[0] === C2S_FS_WRITE)!;
    const nonce = writeMsg[1] | (writeMsg[2] << 8);
    transport.push(buildFsDoneMessage(nonce, FS_DONE_OK, 0xabcdn, 1n));
    await writePromise;

    // Recorded on the writing handle only: to the other consumer this
    // write is an external change, and its editor must reload on the echo.
    expect(writer.lastWrittenHash("a.txt")).toBe(0xabcdn);
    expect(reader.lastWrittenHash("a.txt")).toBeUndefined();

    transport.push(
      buildFsUpdateMessage(7, 1, 0, upsertWithHash("a.txt", "hi", 0xabcdn)),
    );
    expect(seen).toEqual([{ hash: 0xabcdn, suppressed: false }]);
    // Consumed from the writer's map once the echo has been delivered.
    expect(writer.lastWrittenHash("a.txt")).toBeUndefined();
    conn.dispose();
  });

  it("surfaces a read-only server's PERMISSION refusal", async () => {
    // Writes share FEATURE_FS; a BLIT_FS_WRITE=0 server answers each
    // write with FS_DONE PERMISSION instead of withholding a bit.
    const { conn, transport, handle } = await writeReadyHandle();
    const p = handle.writeFile("a", new Uint8Array());
    const writeMsg = transport.sent.find((m) => m[0] === C2S_FS_WRITE)!;
    const nonce = writeMsg[1] | (writeMsg[2] << 8);
    transport.push(buildFsDoneMessage(nonce, FS_DONE_PERMISSION, 0n, 0n));
    await expect(p).rejects.toThrow(/permission denied/);
    conn.dispose();
  });
});

// -- File index (docs/design/fs-search.md) -----------------------------------

/** Hand-build an S2C_FS_INDEX (literal-only LZ4, which real decoders accept). */
function buildIndexResult(
  nonce: number,
  status: number,
  flags: number,
  paths: string[],
): Uint8Array {
  const enc = new TextEncoder();
  const raws = paths.map((p) => enc.encode(p));
  const raw = new Uint8Array(raws.reduce((n, b) => n + 2 + b.length, 0));
  const rv = new DataView(raw.buffer);
  let off = 0;
  for (const b of raws) {
    rv.setUint16(off, b.length, true);
    raw.set(b, off + 2);
    off += 2 + b.length;
  }
  const payload = fsCompressLiteral(raw);
  const msg = new Uint8Array(9 + payload.length);
  const v = new DataView(msg.buffer);
  msg[0] = S2C_FS_INDEX;
  v.setUint16(1, nonce, true);
  msg[3] = status;
  msg[4] = flags;
  v.setUint32(5, paths.length, true);
  msg.set(payload, 9);
  return msg;
}

describe("fs index codec", () => {
  it("C2S builder emits the bytes pinned in Rust", () => {
    // Matches `fs_index_request_roundtrip` in crates/remote/src/fs.rs.
    expect(toHex(buildFsIndexMessage(0x0102, "/tmp/watch me"))).toBe(
      "470201000d002f746d702f7761746368206d65",
    );
  });

  it("result parse: roundtrip, empty list, count mismatch", () => {
    const paths = ["a.txt", "sub/b.txt", ""];
    const msg = buildIndexResult(7, FS_DONE_OK, FS_INDEX_TRUNCATED, paths);
    expect(parseFsIndexResult(msg)).toEqual({
      nonce: 7,
      status: FS_DONE_OK,
      flags: FS_INDEX_TRUNCATED,
      paths,
    });
    expect(
      parseFsIndexResult(buildIndexResult(8, FS_DONE_NOT_FOUND, 0, [])),
    ).toEqual({
      nonce: 8,
      status: FS_DONE_NOT_FOUND,
      flags: 0,
      paths: [],
    });
    const lying = buildIndexResult(9, FS_DONE_OK, 0, ["a"]);
    new DataView(lying.buffer).setUint32(5, 2, true);
    expect(parseFsIndexResult(lying)).toBeNull();
    // A count over the protocol cap is malformed before any decoding.
    const over = buildIndexResult(10, FS_DONE_OK, 0, []);
    new DataView(over.buffer).setUint32(5, FS_INDEX_MAX_COUNT + 1, true);
    expect(parseFsIndexResult(over)).toBeNull();
  });
});

describe("BlitConnection.indexFiles", () => {
  it("resolves paths + truncated from S2C_FS_INDEX", async () => {
    const { conn, transport } = fsReadyConnection();
    const promise = conn.indexFiles("/watched");
    const msg = transport.sent.find((m) => m[0] === C2S_FS_INDEX)!;
    expect(msg).toBeDefined();
    expect(msg[3]).toBe(0); // flags reserved
    expect(new TextDecoder().decode(msg.subarray(6))).toBe("/watched");
    const nonce = msg[1] | (msg[2] << 8);
    transport.push(
      buildIndexResult(nonce, FS_DONE_OK, FS_INDEX_TRUNCATED, [
        "a.txt",
        "sub/b.txt",
      ]),
    );
    await expect(promise).resolves.toEqual({
      paths: ["a.txt", "sub/b.txt"],
      truncated: true,
    });
    conn.dispose();
  });

  it("rejects on a non-OK status", async () => {
    const { conn, transport } = fsReadyConnection();
    const promise = conn.indexFiles("/gone");
    const msg = transport.sent.find((m) => m[0] === C2S_FS_INDEX)!;
    const nonce = msg[1] | (msg[2] << 8);
    transport.push(buildIndexResult(nonce, FS_DONE_NOT_FOUND, 0, []));
    await expect(promise).rejects.toThrow(/not found/);
    conn.dispose();
  });
});

// -- FS_GREP (docs/design/fs-grep.md) ---------------------------------------

/** Frame one record the way the Rust `append_fs_grep_record` does. */
function grepRecord(kind: number, body: number[]): number[] {
  const len = 1 + body.length;
  return [
    len & 0xff,
    (len >> 8) & 0xff,
    (len >> 16) & 0xff,
    (len >> 24) & 0xff,
    kind,
    ...body,
  ];
}
const u16le = (n: number) => [n & 0xff, (n >> 8) & 0xff];
const u32le = (n: number) => [
  n & 0xff,
  (n >> 8) & 0xff,
  (n >> 16) & 0xff,
  (n >> 24) & 0xff,
];
const strBytes = (s: string) => [...new TextEncoder().encode(s)];

function fileRecord(flags: number, n: number, path: string): number[] {
  const pb = strBytes(path);
  return grepRecord(FS_GREP_RECORD_FILE, [
    flags,
    ...u16le(n),
    ...u16le(pb.length),
    ...pb,
  ]);
}
function matchRecord(
  line: number,
  col: number,
  endCol: number,
  text: string,
  endLine = line,
): number[] {
  const tb = strBytes(text);
  return grepRecord(FS_GREP_RECORD_MATCH, [
    ...u32le(line),
    ...u32le(col),
    ...u32le(endLine),
    ...u32le(endCol),
    ...u32le(tb.length),
    ...tb,
  ]);
}

/** Hand-build an S2C_FS_GREP, literal-only LZ4 as real decoders accept. */
function buildGrepResult(
  nonce: number,
  status: number,
  flags: number,
  detail: string,
  records: number[],
): Uint8Array {
  const db = new TextEncoder().encode(detail);
  const payload = fsCompressLiteral(new Uint8Array(records));
  const msg = new Uint8Array(7 + db.length + payload.length);
  const v = new DataView(msg.buffer);
  msg[0] = S2C_FS_GREP;
  v.setUint16(1, nonce, true);
  msg[3] = status;
  msg[4] = flags;
  v.setUint16(5, db.length, true);
  msg.set(db, 7);
  msg.set(payload, 7 + db.length);
  return msg;
}

describe("fs grep codec", () => {
  it("C2S builder emits the bytes pinned in Rust", () => {
    // Matches `fs_grep_request_roundtrip` in crates/remote/src/fs.rs.
    expect(
      toHex(
        buildFsGrepMessage(0x0102, "/tmp/root", "fn \\w+", {
          caseSensitive: true,
          regex: true,
          maxMatches: 500,
          maxPerFile: 50,
        }),
      ),
    ).toBe("48020103f401320009002f746d702f726f6f740600666e205c772b");
  });

  it("defaults to case-insensitive literal with server-default budgets", () => {
    const m = buildFsGrepMessage(1, "/r", "q");
    expect(m[3]).toBe(0);
    const v = new DataView(m.buffer);
    expect(v.getUint16(4, true)).toBe(0);
    expect(v.getUint16(6, true)).toBe(0);
    expect(buildFsGrepMessage(1, "/r", "q", { caseSensitive: true })[3]).toBe(
      FS_GREP_CASE_SENSITIVE,
    );
    expect(buildFsGrepMessage(1, "/r", "q", { regex: true })[3]).toBe(
      FS_GREP_REGEX,
    );
  });

  it("groups matches under their file and flags ignored ones", () => {
    const records = [
      ...fileRecord(0, 2, "src/main.rs"),
      ...matchRecord(41, 4, 6, "    fn main() {"),
      ...matchRecord(99, 0, 2, "fn helper()"),
      ...fileRecord(FS_GREP_FILE_IGNORED, 1, "target/debug/build.rs"),
      ...matchRecord(0, 0, 2, ""),
    ];
    const parsed = parseFsGrepResult(
      buildGrepResult(7, FS_DONE_OK, FS_GREP_TRUNCATED, "", records),
    );
    expect(parsed).toEqual({
      nonce: 7,
      status: FS_DONE_OK,
      flags: FS_GREP_TRUNCATED,
      detail: "",
      files: [
        {
          path: "src/main.rs",
          ignored: false,
          matches: [
            {
              line: 41,
              col: 4,
              endLine: 41,
              endCol: 6,
              text: "    fn main() {",
            },
            { line: 99, col: 0, endLine: 99, endCol: 2, text: "fn helper()" },
          ],
        },
        {
          path: "target/debug/build.rs",
          ignored: true,
          matches: [{ line: 0, col: 0, endLine: 0, endCol: 2, text: "" }],
        },
      ],
    });
  });

  it("carries a regex compile error in detail with no files", () => {
    const parsed = parseFsGrepResult(
      buildGrepResult(8, FS_DONE_INVALID, 0, "unclosed character class", []),
    )!;
    expect(parsed.status).toBe(FS_DONE_INVALID);
    expect(parsed.detail).toBe("unclosed character class");
    expect(parsed.files).toEqual([]);
  });

  it("skips unknown record kinds via record_len", () => {
    const records = [
      ...fileRecord(0, 0, "a"),
      ...grepRecord(0x7f, strBytes("whatever")),
      ...fileRecord(0, 0, "b"),
    ];
    const got = [...fsGrepRecords(new Uint8Array(records))];
    expect(got.map((r) => (r.kind === "file" ? r.path : "?"))).toEqual([
      "a",
      "b",
    ]);
  });

  it("rejects a malformed frame rather than half-decoding it", () => {
    const good = buildGrepResult(1, FS_DONE_OK, 0, "", fileRecord(0, 0, "a"));
    expect(parseFsGrepResult(good.subarray(0, 5))).toBeNull();
    const wrongOpcode = good.slice();
    wrongOpcode[0] = 0x40;
    expect(parseFsGrepResult(wrongOpcode)).toBeNull();
    // A record claiming more body than the payload holds ends iteration.
    const overrun = new Uint8Array([...u32le(0xffff), FS_GREP_RECORD_FILE, 0]);
    expect([...fsGrepRecords(overrun)]).toEqual([]);
  });
});

describe("BlitConnection.grep", () => {
  it("resolves files grouped, ignored last, with the truncated flag", async () => {
    const { conn, transport } = fsReadyConnection();
    const promise = conn.grep("/watched", "needle", {
      caseSensitive: true,
      regex: true,
    });
    const msg = transport.sent.find((m) => m[0] === C2S_FS_GREP)!;
    expect(msg[3]).toBe(FS_GREP_CASE_SENSITIVE | FS_GREP_REGEX);
    const nonce = msg[1] | (msg[2] << 8);
    transport.push(
      buildGrepResult(nonce, FS_DONE_OK, FS_GREP_TRUNCATED, "", [
        ...fileRecord(0, 1, "src/a.rs"),
        ...matchRecord(3, 4, 10, "let needle = 1;"),
        ...fileRecord(FS_GREP_FILE_IGNORED, 1, "target/gen.rs"),
        ...matchRecord(0, 0, 6, "needle"),
      ]),
    );
    await expect(promise).resolves.toEqual({
      truncated: true,
      files: [
        {
          path: "src/a.rs",
          ignored: false,
          matches: [
            {
              line: 3,
              col: 4,
              endLine: 3,
              endCol: 10,
              text: "let needle = 1;",
            },
          ],
        },
        {
          path: "target/gen.rs",
          ignored: true,
          matches: [{ line: 0, col: 0, endLine: 0, endCol: 6, text: "needle" }],
        },
      ],
    });
    conn.dispose();
  });

  it("rejects with the server's own message on a bad regex", async () => {
    const { conn, transport } = fsReadyConnection();
    const promise = conn.grep("/watched", "a[", { regex: true });
    const nonce = (() => {
      const m = transport.sent.find((x) => x[0] === C2S_FS_GREP)!;
      return m[1] | (m[2] << 8);
    })();
    transport.push(
      buildGrepResult(
        nonce,
        FS_DONE_INVALID,
        0,
        "unclosed character class",
        [],
      ),
    );
    await expect(promise).rejects.toThrow(/unclosed character class/);
    conn.dispose();
  });
});
