import { describe, it, expect } from "vitest";
import { BlitConnection } from "../BlitConnection";
import { MockTransport } from "./mock-transport";
import type { BlitWasmModule } from "../TerminalStore";
import { S2C_FRAGMENT, FRAGMENT_FLAG_LAST } from "../types";
import {
  FEATURE_FS_SYNC,
  FS_CLOSED_CONNECTION_LOST,
  FS_CLOSED_ROOT_GONE,
  FS_CONTENT_FULL,
  FS_ENTRY_DIR,
  FS_ENTRY_FILE,
  FS_ENTRY_NO_CONTENT,
  FS_FILE_OK,
  FS_STATUS_NOT_FOUND,
  FS_SYNC_CONTENT,
  FS_SYNC_RECURSIVE,
  FS_UPDATE_RESET,
  FS_UPDATE_SYNC,
  FsMirror,
  type FsRecord,
  appendFsRecord,
  applyFsDelta,
  buildFsAckMessage,
  buildFsFetchMessage,
  buildFsStopMessage,
  buildFsSyncMessage,
  buildFsUpdateMessage,
  fsCompressLiteral,
  fsDecompress,
  fsRecords,
  parseFsFileMessage,
  C2S_FS_ACK,
  C2S_FS_SYNC,
  S2C_FS_CLOSED,
  S2C_FS_FILE,
  S2C_FS_SYNCED,
  S2C_FS_UPDATE,
} from "../fs";

function fromHex(hex: string): Uint8Array {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) {
    out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  }
  return out;
}

function toHex(bytes: Uint8Array): string {
  return [...bytes].map((b) => b.toString(16).padStart(2, "0")).join("");
}

/**
 * Byte fixtures generated by the Rust codecs in `crates/remote/src/fs.rs`
 * (see the matching `wire_fixtures` test there). Both implementations pin
 * the same bytes, so any codec drift fails on one side or the other.
 */
const FIXTURE_SYNC = "400201031900000001000d002f746d702f7761746368206d65";
const FIXTURE_STOP = "410201";
const FIXTURE_ACK = "42020104030201";
const FIXTURE_FETCH = "43030002010b007375622f2546462e62696e";
const FIXTURE_RECORDS =
  "3700000001000500612e747874050000000000000015cd853dfe9c9717a48100008877665544332211efcdab8967452301010500000068656c6c6f2c0000000101030073756200000000000000000000000000000000ed41000000000000000000000000000000000000003400000001080b007375622f2546462e62696e0000100000000000010000000000000080810000ff00000000000000000000000000000000060000000203006f6c640b0000000303007372630300647374";
// FIXTURE_RECORDS compressed by lz4_flex (real matches, not literal-only)
// inside a full S2C_FS_UPDATE(sync_id=0x0102, update_id=7, RESET|SYNC).
const FIXTURE_UPDATE =
  "4102010700000003bc000000f2003700000001000500612e74787405000100f00e15cd853dfe9c9717a48100008877665544332211efcdab89674523010125006068656c6c6f2c3b0062010300737562370006020026ed410c000502001034300020080b3000b12f2546462e62696e0000101f001101060070000080810000ff0900080200f00a060000000203006f6c640b0000000303007372630300647374";
const FIXTURE_FILE = "4209000012000000f00366696c652d636f6e74656e742d6279746573";
const FIXTURE_SYNCED = "40020103000002002f77";

/** The records encoded by FIXTURE_RECORDS, as TS record values. */
function fixtureRecords(): FsRecord[] {
  return [
    {
      kind: "upsert",
      path: "a.txt",
      entryFlags: FS_ENTRY_FILE,
      size: 5,
      mtimeNs: 1_700_000_000_123_456_789n,
      mode: 0o100644,
      hash: 0x0123_4567_89ab_cdef_1122_3344_5566_7788n,
      content: { kind: "full", data: new TextEncoder().encode("hello") },
    },
    {
      kind: "upsert",
      path: "sub",
      entryFlags: FS_ENTRY_DIR,
      size: 0,
      mtimeNs: 0n,
      mode: 0o40755,
      hash: 0n,
      content: { kind: "none" },
    },
    {
      kind: "upsert",
      path: "sub/%FF.bin", // server-escaped non-UTF-8 name, opaque here
      entryFlags: FS_ENTRY_FILE | FS_ENTRY_NO_CONTENT,
      size: 1 << 20,
      mtimeNs: 1n,
      mode: 0o100600,
      hash: 0xffn,
      content: { kind: "none" },
    },
    { kind: "delete", path: "old" },
    { kind: "move", from: "src", to: "dst" },
  ];
}

describe("fs wire fixtures (cross-checked with Rust)", () => {
  it("C2S builders emit the pinned bytes", () => {
    expect(
      toHex(
        buildFsSyncMessage(
          0x0102,
          FS_SYNC_RECURSIVE | FS_SYNC_CONTENT,
          25,
          65536,
          "/tmp/watch me",
        ),
      ),
    ).toBe(FIXTURE_SYNC);
    expect(toHex(buildFsStopMessage(0x0102))).toBe(FIXTURE_STOP);
    expect(toHex(buildFsAckMessage(0x0102, 0x01020304))).toBe(FIXTURE_ACK);
    expect(toHex(buildFsFetchMessage(3, 0x0102, "sub/%FF.bin"))).toBe(
      FIXTURE_FETCH,
    );
  });

  it("record encoder emits the pinned bytes", () => {
    const buf: number[] = [];
    for (const record of fixtureRecords()) {
      appendFsRecord(buf, record);
    }
    expect(toHex(new Uint8Array(buf))).toBe(FIXTURE_RECORDS);
  });

  it("record decoder parses the pinned bytes", () => {
    const decoded = [...fsRecords(fromHex(FIXTURE_RECORDS))];
    const expected = fixtureRecords();
    expect(decoded.length).toBe(expected.length);
    for (let i = 0; i < expected.length; i++) {
      const d = decoded[i];
      const e = expected[i];
      expect(d.kind).toBe(e.kind);
      if (d.kind === "upsert" && e.kind === "upsert") {
        expect(d.path).toBe(e.path);
        expect(d.entryFlags).toBe(e.entryFlags);
        expect(d.size).toBe(e.size);
        expect(d.mtimeNs).toBe(e.mtimeNs);
        expect(d.mode).toBe(e.mode);
        expect(d.hash).toBe(e.hash);
        expect(d.content.kind).toBe(e.content.kind);
        if (d.content.kind === "full" && e.content.kind === "full") {
          expect(toHex(d.content.data)).toBe(toHex(e.content.data));
        }
      } else {
        expect(d).toEqual(e);
      }
    }
  });

  it("applies a Rust-compressed FS_UPDATE (real LZ4 with matches)", () => {
    const mirror = new FsMirror();
    expect(mirror.applyUpdate(fromHex(FIXTURE_UPDATE))).toBe(7);
    // RESET|SYNC: the staged map swapped in.
    expect(mirror.live.size).toBe(3);
    expect(new TextDecoder().decode(mirror.live.get("a.txt")!.content!)).toBe(
      "hello",
    );
    expect(mirror.live.get("sub")!.entryFlags).toBe(FS_ENTRY_DIR);
    const escaped = mirror.live.get("sub/%FF.bin")!;
    expect(escaped.content).toBeNull();
    expect(escaped.size).toBe(1 << 20);
    expect(escaped.hash).toBe(0xffn);
  });

  it("parses a Rust-compressed FS_FILE", () => {
    const parsed = parseFsFileMessage(fromHex(FIXTURE_FILE));
    expect(parsed).not.toBeNull();
    expect(parsed!.nonce).toBe(9);
    expect(parsed!.status).toBe(FS_FILE_OK);
    expect(new TextDecoder().decode(parsed!.data)).toBe("file-content-bytes");
  });
});

function upsertRecords(path: string, content: string): Uint8Array {
  const bytes = new TextEncoder().encode(content);
  const buf: number[] = [];
  appendFsRecord(buf, {
    kind: "upsert",
    path,
    entryFlags: FS_ENTRY_FILE,
    size: bytes.length,
    mtimeNs: 42n,
    mode: 0o644,
    hash: 7n,
    content: { kind: "full", data: bytes },
  });
  return new Uint8Array(buf);
}

function concat(...parts: Uint8Array[]): Uint8Array {
  const out = new Uint8Array(parts.reduce((n, p) => n + p.length, 0));
  let offset = 0;
  for (const p of parts) {
    out.set(p, offset);
    offset += p.length;
  }
  return out;
}

describe("FsMirror", () => {
  it("staged snapshot, live edits, mid-stream restage", () => {
    const mirror = new FsMirror();
    // Snapshot: RESET+SYNC with two files.
    const records = concat(
      upsertRecords("a.txt", "alpha"),
      upsertRecords("d/b.txt", "beta"),
    );
    expect(
      mirror.applyUpdate(
        buildFsUpdateMessage(1, 1, FS_UPDATE_RESET | FS_UPDATE_SYNC, records),
      ),
    ).toBe(1);
    expect(mirror.live.size).toBe(2);
    expect(new TextDecoder().decode(mirror.live.get("a.txt")!.content!)).toBe(
      "alpha",
    );

    // Live delete + move.
    const buf: number[] = [];
    appendFsRecord(buf, { kind: "delete", path: "a.txt" });
    appendFsRecord(buf, { kind: "move", from: "d", to: "e" });
    expect(
      mirror.applyUpdate(buildFsUpdateMessage(1, 2, 0, new Uint8Array(buf))),
    ).toBe(2);
    expect(mirror.live.size).toBe(1);
    expect(new TextDecoder().decode(mirror.live.get("e/b.txt")!.content!)).toBe(
      "beta",
    );

    // Mid-stream RESET without SYNC leaves live untouched…
    expect(
      mirror.applyUpdate(
        buildFsUpdateMessage(
          1,
          3,
          FS_UPDATE_RESET,
          upsertRecords("n.txt", "new"),
        ),
      ),
    ).toBe(3);
    expect(mirror.live.size).toBe(1);
    expect(mirror.live.has("e/b.txt")).toBe(true);
    // …until SYNC swaps atomically.
    expect(
      mirror.applyUpdate(
        buildFsUpdateMessage(1, 4, FS_UPDATE_SYNC, new Uint8Array(0)),
      ),
    ).toBe(4);
    expect(mirror.live.size).toBe(1);
    expect(mirror.live.has("n.txt")).toBe(true);
  });

  it("subtree prefix semantics: 'ab' is not under 'a'", () => {
    const mirror = new FsMirror();
    const records = concat(
      upsertRecords("a", "x"),
      upsertRecords("a/b", "x"),
      upsertRecords("ab", "x"),
      upsertRecords("z", "x"),
    );
    mirror.applyUpdate(
      buildFsUpdateMessage(1, 1, FS_UPDATE_RESET | FS_UPDATE_SYNC, records),
    );
    const buf: number[] = [];
    appendFsRecord(buf, { kind: "delete", path: "a" });
    mirror.applyUpdate(buildFsUpdateMessage(1, 2, 0, new Uint8Array(buf)));
    expect([...mirror.live.keys()].sort()).toEqual(["ab", "z"]);
  });

  it("delta content against the previous ack", () => {
    const mirror = new FsMirror();
    mirror.applyUpdate(
      buildFsUpdateMessage(
        1,
        1,
        FS_UPDATE_RESET | FS_UPDATE_SYNC,
        upsertRecords("f", "hello world"),
      ),
    );
    // COPY(0,6) + INSERT("blit") == "hello blit"
    const ops = new Uint8Array([0x01, 0, 6, 0x02, 4, 0x62, 0x6c, 0x69, 0x74]);
    const buf: number[] = [];
    appendFsRecord(buf, {
      kind: "upsert",
      path: "f",
      entryFlags: FS_ENTRY_FILE,
      size: 10,
      mtimeNs: 43n,
      mode: 0o644,
      hash: 8n,
      content: { kind: "delta", ops },
    });
    mirror.applyUpdate(buildFsUpdateMessage(1, 2, 0, new Uint8Array(buf)));
    expect(new TextDecoder().decode(mirror.live.get("f")!.content!)).toBe(
      "hello blit",
    );
  });

  it("metadata-only upsert keeps previous content", () => {
    const mirror = new FsMirror();
    mirror.applyUpdate(
      buildFsUpdateMessage(
        1,
        1,
        FS_UPDATE_RESET | FS_UPDATE_SYNC,
        upsertRecords("f", "keep"),
      ),
    );
    const buf: number[] = [];
    appendFsRecord(buf, {
      kind: "upsert",
      path: "f",
      entryFlags: FS_ENTRY_FILE,
      size: 4,
      mtimeNs: 99n,
      mode: 0o600,
      hash: 7n,
      content: { kind: "none" },
    });
    mirror.applyUpdate(buildFsUpdateMessage(1, 2, 0, new Uint8Array(buf)));
    const node = mirror.live.get("f")!;
    expect(node.mode).toBe(0o600);
    expect(new TextDecoder().decode(node.content!)).toBe("keep");
  });

  it("rejects an oversized declared decompression length", () => {
    // A hand-forged FS_UPDATE whose LZ4 size prefix declares 1 GiB.
    const msg = new Uint8Array(8 + 4 + 16);
    const v = new DataView(msg.buffer);
    msg[0] = S2C_FS_UPDATE;
    v.setUint16(1, 1, true);
    v.setUint32(3, 1, true);
    msg[7] = 0;
    v.setUint32(8, 1 << 30, true);
    expect(new FsMirror().applyUpdate(msg)).toBeNull();

    const file = new Uint8Array(4 + 4 + 16);
    const fv = new DataView(file.buffer);
    file[0] = S2C_FS_FILE;
    fv.setUint16(1, 7, true);
    file[3] = FS_FILE_OK;
    fv.setUint32(4, 1 << 30, true);
    expect(parseFsFileMessage(file)).toBeNull();
  });

  it("skips unknown record kinds via record_len", () => {
    const buf: number[] = [4, 0, 0, 0, 0x7f, 1, 2, 3];
    appendFsRecord(buf, { kind: "delete", path: "x" });
    const decoded = [...fsRecords(new Uint8Array(buf))];
    expect(decoded).toEqual([{ kind: "delete", path: "x" }]);
  });
});

describe("fs LZ4 helpers", () => {
  it("literal-only compression round-trips", () => {
    for (const len of [0, 1, 14, 15, 16, 100, 300, 5000]) {
      const data = new Uint8Array(len);
      for (let i = 0; i < len; i++) data[i] = i & 0xff;
      const out = fsDecompress(fsCompressLiteral(data));
      expect(out).not.toBeNull();
      expect(toHex(out!)).toBe(toHex(data));
    }
  });

  it("applyFsDelta handles multi-byte LEB128 and rejects junk", () => {
    const base = new Uint8Array(300);
    for (let i = 0; i < 300; i++) base[i] = i & 0xff;
    // COPY(offset=200 → 0xC8 0x01, len=100)
    const ops = new Uint8Array([0x01, 0xc8, 0x01, 100]);
    const out = applyFsDelta(base, ops)!;
    expect(toHex(out)).toBe(toHex(base.subarray(200, 300)));
    // COPY out of range.
    expect(
      applyFsDelta(base, new Uint8Array([0x01, 0xc8, 0x02, 100])),
    ).toBeNull();
    // Unknown op.
    expect(applyFsDelta(base, new Uint8Array([0x03]))).toBeNull();
    // Truncated INSERT.
    expect(applyFsDelta(base, new Uint8Array([0x02, 9, 1]))).toBeNull();
  });
});

// -- Connection-level flow ---------------------------------------------------

class FakeTerminal {
  constructor(_r: number, _c: number, _pw: number, _ph: number) {}
  set_font_family(_f: string) {}
  set_font_size(_s: number) {}
  set_default_colors(..._a: number[]) {}
  set_ansi_color(..._a: number[]) {}
  feed_compressed(_d: Uint8Array) {}
  invalidate_render_cache() {}
  title() {
    return "";
  }
  free() {}
}

const wasm = { Terminal: FakeTerminal } as unknown as BlitWasmModule;

function fsReadyConnection(): {
  conn: BlitConnection;
  transport: MockTransport;
} {
  const transport = new MockTransport();
  const conn = new BlitConnection({
    id: "test",
    transport,
    wasm,
    autoConnect: false,
  });
  transport.pushHello(1, FEATURE_FS_SYNC);
  transport.pushReady();
  return { conn, transport };
}

function pushSynced(
  transport: MockTransport,
  nonce: number,
  syncId: number,
  status: number,
  detail: string,
) {
  const detailBytes = new TextEncoder().encode(detail);
  const msg = new Uint8Array(8 + detailBytes.length);
  const v = new DataView(msg.buffer);
  msg[0] = S2C_FS_SYNCED;
  v.setUint16(1, nonce, true);
  v.setUint16(3, syncId, true);
  msg[5] = status;
  v.setUint16(6, detailBytes.length, true);
  msg.set(detailBytes, 8);
  transport.push(msg);
}

describe("BlitConnection.syncFs", () => {
  it("full flow: sync, snapshot, records, ack, fetch, close", async () => {
    const { conn, transport } = fsReadyConnection();
    expect(conn.getSnapshot().supportsFsSync).toBe(true);

    const seen: FsRecord[] = [];
    let syncs = 0;
    let closedReason: number | null = null;
    const handlePromise = conn.syncFs("/watched", {
      content: true,
      onRecord: (r) => seen.push(r),
      onSync: () => syncs++,
      onClosed: (reason) => (closedReason = reason),
    });

    // The C2S_FS_SYNC went out; answer it.
    const syncMsg = transport.sent.find((m) => m[0] === C2S_FS_SYNC)!;
    expect(syncMsg).toBeDefined();
    const nonce = syncMsg[1] | (syncMsg[2] << 8);
    pushSynced(transport, nonce, 5, 0, "/watched");
    const handle = await handlePromise;
    expect(handle.syncId).toBe(5);
    expect(handle.root).toBe("/watched");

    // Snapshot in two updates: RESET, then SYNC.
    transport.push(
      buildFsUpdateMessage(5, 1, FS_UPDATE_RESET, upsertRecords("a", "one")),
    );
    // Staging active: live is still empty.
    expect(handle.live.size).toBe(0);
    transport.push(
      buildFsUpdateMessage(5, 2, FS_UPDATE_SYNC, upsertRecords("b", "two")),
    );
    expect(syncs).toBe(1);
    expect([...handle.live.keys()].sort()).toEqual(["a", "b"]);
    expect(seen.length).toBe(2);

    // Both updates were acked cumulatively as they arrived.
    const acks = transport.sent.filter((m) => m[0] === C2S_FS_ACK);
    expect(acks.length).toBe(2);
    const last = acks[acks.length - 1];
    expect(last[1] | (last[2] << 8)).toBe(5);
    expect(new DataView(last.buffer, 3, 4).getUint32(0, true)).toBe(2);

    // Fetch.
    const dataPromise = handle.fetch("a");
    const fetchMsg = transport.sent.filter((m) => m[0] === 0x43).pop()!;
    const fetchNonce = fetchMsg[1] | (fetchMsg[2] << 8);
    const payload = fsCompressLiteral(new TextEncoder().encode("bytes"));
    const fileMsg = new Uint8Array(4 + payload.length);
    fileMsg[0] = S2C_FS_FILE;
    fileMsg[1] = fetchNonce & 0xff;
    fileMsg[2] = (fetchNonce >> 8) & 0xff;
    fileMsg[3] = FS_FILE_OK;
    fileMsg.set(payload, 4);
    transport.push(fileMsg);
    expect(new TextDecoder().decode(await dataPromise)).toBe("bytes");

    // Server closes the sync.
    transport.push(new Uint8Array([S2C_FS_CLOSED, 5, 0, FS_CLOSED_ROOT_GONE]));
    expect(closedReason).toBe(FS_CLOSED_ROOT_GONE);

    conn.dispose();
  });

  it("reassembles a fragmented FS_UPDATE", async () => {
    const { conn, transport } = fsReadyConnection();
    const handlePromise = conn.syncFs("/w");
    const syncMsg = transport.sent.find((m) => m[0] === C2S_FS_SYNC)!;
    pushSynced(transport, syncMsg[1] | (syncMsg[2] << 8), 1, 0, "/w");
    const handle = await handlePromise;

    const update = buildFsUpdateMessage(
      1,
      1,
      FS_UPDATE_RESET | FS_UPDATE_SYNC,
      upsertRecords("frag.txt", "reassembled"),
    );
    const mid = Math.floor(update.length / 2);
    transport.push(
      concat(new Uint8Array([S2C_FRAGMENT, 0]), update.subarray(0, mid)),
    );
    expect(handle.live.size).toBe(0);
    transport.push(
      concat(
        new Uint8Array([S2C_FRAGMENT, FRAGMENT_FLAG_LAST]),
        update.subarray(mid),
      ),
    );
    expect(
      new TextDecoder().decode(handle.live.get("frag.txt")!.content!),
    ).toBe("reassembled");
    conn.dispose();
  });

  it("rejects a failed sync with the server detail", async () => {
    const { conn, transport } = fsReadyConnection();
    const handlePromise = conn.syncFs("/missing");
    const syncMsg = transport.sent.find((m) => m[0] === C2S_FS_SYNC)!;
    pushSynced(
      transport,
      syncMsg[1] | (syncMsg[2] << 8),
      0xffff,
      FS_STATUS_NOT_FOUND,
      "no such directory",
    );
    await expect(handlePromise).rejects.toThrow(/not found: no such directory/);
    conn.dispose();
  });

  it("closes live syncs when the server session restarts", async () => {
    const { conn, transport } = fsReadyConnection();
    let closedReason: number | null = null;
    const handlePromise = conn.syncFs("/w", {
      onClosed: (reason) => (closedReason = reason),
    });
    const syncMsg = transport.sent.find((m) => m[0] === C2S_FS_SYNC)!;
    pushSynced(transport, syncMsg[1] | (syncMsg[2] << 8), 2, 0, "/w");
    await handlePromise;
    transport.pushHello(1, FEATURE_FS_SYNC);
    expect(closedReason).toBe(FS_CLOSED_CONNECTION_LOST);
    conn.dispose();
  });

  it("refuses syncFs without the feature bit", async () => {
    const transport = new MockTransport();
    const conn = new BlitConnection({
      id: "test",
      transport,
      wasm,
      autoConnect: false,
    });
    transport.pushHello(1, 0);
    transport.pushReady();
    expect(conn.getSnapshot().supportsFsSync).toBe(false);
    await expect(conn.syncFs("/w")).rejects.toThrow(/does not support/);
    conn.dispose();
  });
});
