import { describe, expect, it } from "vitest";
import {
  GIT_CLOSED_REPO_GONE,
  GIT_COMMIT_LOSSY_ENCODING,
  GIT_DIFF_RENAMES,
  GIT_ENDPOINT_COMMIT,
  GIT_ENDPOINT_WORKTREE,
  GIT_INDEX_INTENT_TO_ADD,
  GIT_LOG_FIRST_PARENT,
  GIT_OID_NONE,
  GIT_OPEN_STATUS,
  GIT_OPEN_WATCH,
  GIT_OID_FORMAT_SHA1,
  GIT_PATCH_CHAR_SPANS,
  GIT_REPO_LINKED,
  GIT_STATUS_OK,
  GIT_UPSTREAM_COUNTS_VALID,
  GitStateMirror,
  type GitOid,
  appendGitStateRecord,
  gitCommitRecords,
  gitDiffRecords,
  gitIndexRecords,
  gitOidFromHex,
  gitOidHex,
  gitPatchRecords,
  gitStateRecords,
  gitTreeRecords,
  msgGitAck,
  msgGitBase,
  msgGitBlob,
  msgGitCancel,
  msgGitClose,
  msgGitClosed,
  msgGitDiff,
  msgGitIndex,
  msgGitLog,
  msgGitLogAck,
  msgGitLogPage,
  msgGitLogUnwatch,
  msgGitLogWatch,
  msgGitOpen,
  msgGitPatch,
  msgGitResolve,
  msgGitResolveResp,
  msgGitState,
  msgGitTree,
  GIT_COMMITS_MORE,
  parseGitBaseResp,
  parseGitClosed,
  parseGitLogPage,
  parseGitRepo,
  parseGitResolveResp,
  parseGitState,
} from "../git";

function hex(bytes: Uint8Array): string {
  return [...bytes].map((b) => b.toString(16).padStart(2, "0")).join("");
}

function fromHex(text: string): Uint8Array {
  const out = new Uint8Array(text.length / 2);
  for (let i = 0; i < out.length; i++) {
    out[i] = Number.parseInt(text.slice(i * 2, i * 2 + 2), 16);
  }
  return out;
}

/** A fixture oid: `fill` over the SHA-1 width, zero-padded to 32 bytes. */
function oid(fill: number): GitOid {
  const out = new Uint8Array(32);
  out.fill(fill, 0, 20);
  return out;
}

/** Hex of a fixture oid as it appears on the wire. */
function o(fill: number): string {
  return hex(oid(fill));
}

const ZERO_OID = "0".repeat(64);

/**
 * Byte fixtures generated by the Rust codecs in `crates/remote/src/git.rs`
 * (see the matching `wire_fixtures` test there). Both implementations pin
 * the same bytes, so any codec drift fails on one side or the other.
 * Buffers that cross LZ4 are pinned uncompressed.
 */
describe("git wire fixtures (cross-checked with Rust)", () => {
  it("builds every C2S message byte-identically", () => {
    expect(
      hex(
        msgGitOpen(0x0102, GIT_OPEN_WATCH | GIT_OPEN_STATUS, 50, 500, "/repo"),
      ),
    ).toBe("500201033200f40105002f7265706f");
    expect(hex(msgGitClose(7))).toBe("510700");
    expect(hex(msgGitAck(7, 0x01020304))).toBe("52070004030201");
    expect(
      hex(
        msgGitLog({
          nonce: 3,
          repoId: 7,
          flags: GIT_LOG_FIRST_PARENT,
          limit: 100,
          path: "src",
          tips: [oid(0xaa)],
          hides: [oid(0xbb)],
        }),
      ),
    ).toBe(`530300070001640003007372630100${o(0xaa)}0100${o(0xbb)}`);
    expect(hex(msgGitTree(4, 7, oid(0xcc), "dir/%FF"))).toBe(
      `5404000700${o(0xcc)}07006469722f254646`,
    );
    expect(hex(msgGitBlob(5, 7, oid(0xdd), "", 1 << 20))).toBe(
      `5505000700${o(0xdd)}000000001000`,
    );
    const old = { kind: GIT_ENDPOINT_COMMIT, oid: oid(0x11) };
    const worktree = { kind: GIT_ENDPOINT_WORKTREE, oid: GIT_OID_NONE };
    expect(
      hex(
        msgGitDiff({
          nonce: 6,
          repoId: 7,
          flags: GIT_DIFF_RENAMES,
          old,
          new: worktree,
          path: "",
        }),
      ),
    ).toBe(`56060007000101${o(0x11)}04${ZERO_OID}0000`);
    expect(
      hex(
        msgGitPatch({
          nonce: 8,
          repoId: 7,
          flags: GIT_DIFF_RENAMES | GIT_PATCH_CHAR_SPANS,
          context: 5,
          old,
          new: worktree,
          path: "a.txt",
          maxLen: 0,
        }),
      ),
    ).toBe(`5708000700410501${o(0x11)}04${ZERO_OID}0500612e74787400000000`);
    expect(hex(msgGitIndex(9, 7, "sub"))).toBe("58090007000300737562");
    expect(hex(msgGitCancel(10))).toBe("590a00");
    expect(hex(msgGitBase(11, 7, [oid(0xaa), oid(0xbb)]))).toBe(
      `5a0b00070002${o(0xaa)}${o(0xbb)}`,
    );
    expect(hex(msgGitResolve(12, 7, "main..dev"))).toBe(
      "5b0c00070009006d61696e2e2e646576",
    );
    expect(hex(msgGitLogWatch(1, 7, GIT_LOG_FIRST_PARENT, 100, "main"))).toBe(
      "5c0100070001640004006d61696e",
    );
    expect(hex(msgGitLogUnwatch(1, 7))).toBe("5d01000700");
    expect(hex(msgGitLogAck(1, 7, 0x01020304))).toBe("5e0100070004030201");
  });

  it("parses the pinned S2C messages", () => {
    const repo = parseGitRepo(
      fromHex("500201010000000802002f7707002f772f2e676974"),
    );
    expect(repo).toEqual({
      nonce: 0x0102,
      repoId: 1,
      status: GIT_STATUS_OK,
      oidFormat: GIT_OID_FORMAT_SHA1,
      flags: GIT_REPO_LINKED,
      workdir: "/w",
      gitdir: "/w/.git",
    });
    expect(hex(msgGitClosed(1, GIT_CLOSED_REPO_GONE))).toBe("52010001");
    expect(parseGitClosed(fromHex("52010001"))).toEqual([
      1,
      GIT_CLOSED_REPO_GONE,
    ]);
    const base = parseGitBaseResp(fromHex(`5a0b000001${o(0xab)}`));
    expect(base?.[0]).toBe(11);
    expect(base?.[1]).toBe(GIT_STATUS_OK);
    expect(hex(base![2][0])).toBe(o(0xab));

    // GIT_RESOLVE reply, pinned against the Rust fixture.
    expect(
      hex(msgGitResolveResp(12, GIT_STATUS_OK, [oid(0xcc)], [oid(0xdd)])),
    ).toBe(`5b0c00000100${o(0xcc)}0100${o(0xdd)}`);
    const resolved = parseGitResolveResp(
      fromHex(`5b0c00000100${o(0xcc)}0100${o(0xdd)}`),
    );
    expect(resolved?.nonce).toBe(12);
    expect(resolved?.status).toBe(GIT_STATUS_OK);
    expect(hex(resolved!.tips[0])).toBe(o(0xcc));
    expect(hex(resolved!.hides[0])).toBe(o(0xdd));

    // GIT_LOG_PAGE crosses LZ4; round-trip through the builder and parser.
    const page = parseGitLogPage(
      msgGitLogPage(
        1,
        42,
        GIT_STATUS_OK,
        GIT_COMMITS_MORE,
        [oid(0xee)],
        fromHex("7265637300"),
      ),
    );
    expect(page?.logId).toBe(1);
    expect(page?.updateId).toBe(42);
    expect(page?.status).toBe(GIT_STATUS_OK);
    expect(page?.flags).toBe(GIT_COMMITS_MORE);
    expect(hex(page!.frontier[0])).toBe(o(0xee));
    expect(hex(page!.records)).toBe("7265637300");
  });

  const STATE_RECORDS =
    "33000000010001010101010101010101010101010101010101010000000000000000000000000f00726566732f68656164732f6d61696e35000000050202000000030000000f00726566732f68656164732f6d61696e1800726566732f72656d6f7465732f6f726967696e2f6d61696e";

  it("decodes the pinned state records", () => {
    const records = [...gitStateRecords(fromHex(STATE_RECORDS))];
    expect(records).toHaveLength(2);
    expect(records[0]).toMatchObject({
      kind: "head",
      flags: 0,
      name: "refs/heads/main",
    });
    expect(records[1]).toMatchObject({
      kind: "upstream",
      flags: GIT_UPSTREAM_COUNTS_VALID,
      ahead: 2,
      behind: 3,
      name: "refs/heads/main",
      upstream: "refs/remotes/origin/main",
    });
  });

  it("re-encodes the pinned state records byte-identically", () => {
    const buf: number[] = [];
    for (const record of gitStateRecords(fromHex(STATE_RECORDS))) {
      appendGitStateRecord(buf, record);
    }
    expect(hex(new Uint8Array(buf))).toBe(STATE_RECORDS);
  });

  it("decodes the pinned commit records", () => {
    const records = [
      ...gitCommitRecords(
        fromHex(
          "bf00000001010a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0000000000000000000000000b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b000000000000000000000000010c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c00000000000000000000000000f15365000000003c0001f1536500000000d4fe0a00416e6e20417574686f720f00616e6e406578616d706c652e636f6d0d0043616d20436f6d6d69747465720f0063616d406578616d706c652e636f6d070000007375626a656374320000000203a48100000d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0000000000000000000000000a007372632f6c69622e7273",
        ),
      ),
    ];
    expect(records).toHaveLength(2);
    const commit = records[0];
    if (commit.kind !== "commit") throw new Error("expected commit");
    expect(commit.flags).toBe(GIT_COMMIT_LOSSY_ENCODING);
    expect(gitOidHex(commit.oid)).toBe("0a".repeat(20));
    expect(commit.parents).toHaveLength(1);
    expect(commit.authorTime).toBe(1_700_000_000n);
    expect(commit.authorTz).toBe(60);
    expect(commit.committerTime).toBe(1_700_000_001n);
    expect(commit.committerTz).toBe(-300);
    expect(commit.authorName).toBe("Ann Author");
    expect(commit.committerEmail).toBe("cam@example.com");
    expect(commit.message).toBe("subject");
    expect(records[1]).toMatchObject({
      kind: "pathAt",
      mode: 0o100644,
      path: "src/lib.rs",
    });
  });

  it("decodes the pinned tree, diff, patch, and index records", () => {
    const tree = [
      ...gitTreeRecords(
        fromHex(
          "2b0000000202004000000e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e00000000000000000000000003007372632f0000000203a48100000f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f00000000000000000000000007002546462e62696e",
        ),
      ),
    ];
    expect(tree.map((e) => e.name)).toEqual(["src", "%FF.bin"]);
    expect(tree[0].mode).toBe(0o40000);

    const diff = [
      ...gitDiffRecords(
        fromHex(
          "210000000410101010101010101010101010101010101010100000000000000000000000005e00000003525a00a4810000a48100001111111111111111111111111111111111111111000000000000000000000000121212121212121212121212121212121212121200000000000000000000000007006f6c642e74787407006e65772e747874",
        ),
      ),
    ];
    expect(diff[0]).toMatchObject({ kind: "base" });
    expect(diff[1]).toMatchObject({
      kind: "entry",
      st: "R".charCodeAt(0),
      similarity: 90,
      oldPath: "old.txt",
      newPath: "new.txt",
    });

    const patch = [
      ...gitPatchRecords(
        fromHex(
          "1000000001000500612e7478740500612e7478742f0000000201000000010000000500000068656c6c6f0500000068616c6c6f010001000000010000000100010000000100000009000000030300000003000000",
        ),
      ),
    ];
    expect(patch[0]).toMatchObject({
      kind: "file",
      oldPath: "a.txt",
      newPath: "a.txt",
    });
    const row = patch[1];
    if (row.kind !== "row") throw new Error("expected row");
    expect(new TextDecoder().decode(row.oldText)).toBe("hello");
    expect(new TextDecoder().decode(row.newText)).toBe("hallo");
    expect(row.oldSpans).toEqual([[1, 1]]);
    expect(row.newSpans).toEqual([[1, 1]]);
    expect(patch[2]).toMatchObject({ kind: "gap", oldLine: 3, newLine: 3 });

    const index = [
      ...gitIndexRecords(
        fromHex(
          "3e000000040001a4810000050000000000000000002a36fe9c971714141414141414141414141414141414141414140000000000000000000000000500612e747874",
        ),
      ),
    ];
    expect(index[0]).toMatchObject({
      kind: "entry",
      stage: 0,
      iflags: GIT_INDEX_INTENT_TO_ADD,
      mode: 0o100644,
      size: 5,
      path: "a.txt",
    });
    expect(index[0].mtimeNs).toBe(1_700_000_000_000_000_000n);
  });
});

describe("git state mirror", () => {
  it("applies snapshots as whole-state replacement", () => {
    const first: number[] = [];
    appendGitStateRecord(first, {
      kind: "head",
      flags: 0,
      oid: oid(1),
      name: "refs/heads/main",
    });
    appendGitStateRecord(first, {
      kind: "ref",
      flags: 0,
      oid: oid(1),
      peeled: GIT_OID_NONE,
      name: "refs/heads/main",
    });
    appendGitStateRecord(first, {
      kind: "status",
      staged: "M".charCodeAt(0),
      unstaged: " ".charCodeAt(0),
      flags: 0,
      oldPath: "",
      path: "a.txt",
    });
    const mirror = new GitStateMirror();
    expect(mirror.applyState(msgGitState(7, 1, 0, new Uint8Array(first)))).toBe(
      1,
    );
    expect(mirror.head?.name).toBe("refs/heads/main");
    expect(mirror.refs.size).toBe(1);
    expect(mirror.status).toHaveLength(1);

    // The next snapshot replaces everything — no merging.
    const second: number[] = [];
    appendGitStateRecord(second, {
      kind: "head",
      flags: 0,
      oid: oid(2),
      name: "refs/heads/dev",
    });
    expect(
      mirror.applyState(msgGitState(7, 2, 0, new Uint8Array(second))),
    ).toBe(2);
    expect(mirror.head?.name).toBe("refs/heads/dev");
    expect(mirror.refs.size).toBe(0);
    expect(mirror.status).toHaveLength(0);
  });

  it("rejects an oversized declared LZ4 size before allocating", () => {
    const msg: number[] = [0x51, 7, 0, 1, 0, 0, 0, 0];
    // Declared decompressed size of 1 GiB.
    msg.push(0x00, 0x00, 0x00, 0x40);
    msg.push(...new Array(16).fill(0));
    expect(new GitStateMirror().applyState(new Uint8Array(msg))).toBeNull();
    expect(parseGitState(new Uint8Array(msg))).toBeNull();
  });

  it("skips unknown record kinds via record_len", () => {
    const buf: number[] = [];
    // A future record kind 0x7F with 3 payload bytes.
    buf.push(4, 0, 0, 0, 0x7f, 1, 2, 3);
    appendGitStateRecord(buf, {
      kind: "op",
      op: 1,
      oid: oid(9),
      detail: "",
    });
    const records = [...gitStateRecords(new Uint8Array(buf))];
    expect(records).toHaveLength(1);
    expect(records[0].kind).toBe("op");
  });

  it("ends the payload on a malformed record", () => {
    // A HEAD record (kind 0x01) claiming 2 body bytes but only holding the
    // kind byte — its decoder overruns. It must stop iteration, not skip,
    // so a following valid record is NOT yielded (matches the Rust codec).
    const buf: number[] = [];
    buf.push(2, 0, 0, 0, 0x01, 0x00); // truncated HEAD
    appendGitStateRecord(buf, {
      kind: "op",
      op: 1,
      oid: oid(9),
      detail: "",
    });
    const records = [...gitStateRecords(new Uint8Array(buf))];
    expect(records).toHaveLength(0);
  });
});

describe("git oid helpers", () => {
  it("round-trips hex", () => {
    const parsed = gitOidFromHex("0a".repeat(20));
    expect(parsed).not.toBeNull();
    expect(gitOidHex(parsed!)).toBe("0a".repeat(20));
    expect(gitOidFromHex("xyz")).toBeNull();
  });
});
