import { describe, expect, it } from "vitest";
import {
  LSP_CAP_DEFINITION,
  LSP_CAP_HOVER,
  LSP_CAP_RENAME,
  LSP_CLOSED_BACKEND_FAILED,
  LSP_CLOSED_ROOT_GONE,
  LSP_DIAG_FULL,
  LSP_DIAG_UNNECESSARY,
  LSP_HASH_NONE,
  LSP_ID_INVALID,
  LSP_MARKUP_MARKDOWN,
  LSP_MARKUP_PLAIN,
  LSP_OPEN_DIAGS,
  LSP_OPEN_WATCH,
  LSP_PHASE_INDEXING,
  LSP_PHASE_READY,
  LSP_PROGRESS_UNKNOWN,
  LSP_QUERY_DEFINITION,
  LSP_SEVERITY_ERROR,
  LSP_SEVERITY_WARNING,
  LSP_STATUS_NOT_FOUND,
  LSP_STATUS_OK,
  LSP_STREAM_DIAG,
  LSP_SYMBOL_DEPRECATED,
  LspDiagMirror,
  LspStateMirror,
  type LspDiagRecord,
  type LspHash,
  type LspQueryRecord,
  appendLspDiagRecord,
  appendLspQueryRecord,
  appendLspServersRecord,
  appendLspStateRecord,
  lspDiagRecords,
  lspQueryRecords,
  lspServersRecords,
  lspStateRecords,
  msgLspAck,
  msgLspCancel,
  msgLspClose,
  msgLspClosed,
  msgLspDiag,
  msgLspOpen,
  msgLspOpened,
  msgLspQuery,
  msgLspQueryResp,
  msgLspServers,
  msgLspServersResp,
  msgLspState,
  msgLspStop,
  msgLspStopped,
  parseLspClosed,
  parseLspDiag,
  parseLspOpened,
  parseLspQueryResp,
  parseLspServersResp,
  parseLspState,
  parseLspStopped,
} from "../lsp";

function hex(bytes: Uint8Array): string {
  return [...bytes].map((b) => b.toString(16).padStart(2, "0")).join("");
}

/** A fixture hash: `fill` over all 16 bytes. */
function hash(fill: number): LspHash {
  return new Uint8Array(16).fill(fill);
}

/**
 * Byte fixtures generated by the Rust codecs in `crates/remote/src/lsp.rs`
 * (see the matching `wire_fixtures` test there). Both implementations pin
 * the same bytes, so any codec drift fails on one side or the other.
 * Buffers that cross LZ4 are pinned uncompressed.
 */
describe("lsp wire fixtures (cross-checked with Rust)", () => {
  it("builds every pinned message byte-identically", () => {
    expect(
      hex(msgLspOpen(0x0102, LSP_OPEN_WATCH | LSP_OPEN_DIAGS, 500, "/src")),
    ).toBe("60020103f40104002f737263");
    expect(hex(msgLspClose(7))).toBe("610700");
    expect(hex(msgLspAck(7, LSP_STREAM_DIAG, 0x01020304))).toBe(
      "6207000104030201",
    );
    expect(
      hex(
        msgLspQuery({
          nonce: 3,
          lspId: 7,
          kind: LSP_QUERY_DEFINITION,
          flags: 0,
          line: 10,
          col: 4,
          path: "a.rs",
          arg: "",
        }),
      ),
    ).toBe("630300070001000a000000040000000400612e72730000");
    expect(hex(msgLspCancel(10))).toBe("640a00");
    expect(hex(msgLspServers(11))).toBe("650b00");
    expect(hex(msgLspStop(12, 2))).toBe("660c000200");
    expect(hex(msgLspOpened(5, 1, LSP_STATUS_OK, 0, "/w", ""))).toBe(
      "6005000100000002002f770000",
    );
    expect(hex(msgLspClosed(1, LSP_CLOSED_ROOT_GONE))).toBe("64010001");
    expect(hex(msgLspStopped(6, LSP_STATUS_OK))).toBe("66060000");
  });

  it("pins the uncompressed record buffers", () => {
    const file: number[] = [];
    appendLspDiagRecord(file, {
      kind: "file",
      hash: hash(0xab),
      n: 1,
      path: "a.rs",
    });
    expect(hex(new Uint8Array(file))).toBe(
      `1900000001${"ab".repeat(16)}01000400612e7273`,
    );
    const markup: number[] = [];
    appendLspQueryRecord(markup, {
      kind: "markup",
      format: LSP_MARKUP_MARKDOWN,
      text: "hi",
    });
    expect(hex(new Uint8Array(markup))).toBe("080000000201020000006869");
  });
});

describe("lsp message roundtrips", () => {
  it("parses S2C_LSP_OPENED", () => {
    expect(
      parseLspOpened(msgLspOpened(7, 1, LSP_STATUS_OK, 0, "/src", "")),
    ).toEqual({
      nonce: 7,
      lspId: 1,
      status: LSP_STATUS_OK,
      flags: 0,
      root: "/src",
      detail: "",
    });
    const opened = parseLspOpened(
      msgLspOpened(
        8,
        LSP_ID_INVALID,
        LSP_STATUS_NOT_FOUND,
        0,
        "",
        "gopls: not found on PATH",
      ),
    );
    expect(opened?.lspId).toBe(LSP_ID_INVALID);
    expect(opened?.detail).toBe("gopls: not found on PATH");
  });

  it("round-trips the LZ4 responses", () => {
    const records: number[] = [];
    appendLspStateRecord(records, {
      kind: "server",
      serverRef: 1,
      phase: LSP_PHASE_INDEXING,
      progressPct: 42,
      caps: LSP_CAP_DEFINITION | LSP_CAP_HOVER,
      epoch: 2,
      refusedEdits: 1,
      rss: 3n << 30n,
      id: "rust-analyzer",
      msg: "indexing 42%",
    });
    const state = parseLspState(msgLspState(1, 5, 0, new Uint8Array(records)));
    expect(state).not.toBeNull();
    const [lspId, stateId, flags, decoded] = state!;
    expect([lspId, stateId, flags]).toEqual([1, 5, 0]);
    expect(hex(decoded)).toBe(hex(new Uint8Array(records)));

    expect(
      parseLspDiag(msgLspDiag(1, 6, LSP_DIAG_FULL, new Uint8Array(0))),
    ).toEqual([1, 6, LSP_DIAG_FULL, new Uint8Array(0)]);
    expect(
      parseLspQueryResp(
        msgLspQueryResp(3, LSP_STATUS_OK, 0, new Uint8Array(0)),
      ),
    ).toEqual([3, LSP_STATUS_OK, 0, new Uint8Array(0)]);
    expect(
      parseLspServersResp(
        msgLspServersResp(4, LSP_STATUS_OK, 0, new Uint8Array(0)),
      ),
    ).toEqual([4, LSP_STATUS_OK, 0, new Uint8Array(0)]);
    expect(parseLspClosed(msgLspClosed(1, LSP_CLOSED_BACKEND_FAILED))).toEqual([
      1,
      LSP_CLOSED_BACKEND_FAILED,
    ]);
    expect(parseLspStopped(msgLspStopped(5, LSP_STATUS_OK))).toEqual([
      5,
      LSP_STATUS_OK,
    ]);
  });
});

describe("lsp record codecs", () => {
  it("round-trips state records", () => {
    const record = {
      kind: "server",
      serverRef: 2,
      phase: LSP_PHASE_READY,
      progressPct: LSP_PROGRESS_UNKNOWN,
      caps: LSP_CAP_RENAME,
      epoch: 0,
      refusedEdits: 0,
      rss: 0n,
      id: "gopls",
      msg: "",
    } as const;
    const buf: number[] = [];
    appendLspStateRecord(buf, record);
    expect([...lspStateRecords(new Uint8Array(buf))]).toEqual([record]);
  });

  it("round-trips servers records", () => {
    const record = {
      kind: "server",
      serverRef: 2,
      phase: LSP_PHASE_READY,
      progressPct: 100,
      caps: 0x3f,
      epoch: 1,
      refusedEdits: 0,
      rss: 1n << 20n,
      id: "gopls",
      msg: "ready",
      root: "/work/api",
    } as const;
    const buf: number[] = [];
    appendLspServersRecord(buf, record);
    expect([...lspServersRecords(new Uint8Array(buf))]).toEqual([record]);
  });

  it("round-trips diag records", () => {
    const records: LspDiagRecord[] = [
      { kind: "file", hash: hash(0xab), n: 1, path: "src/lib.rs" },
      {
        kind: "diag",
        severity: LSP_SEVERITY_ERROR,
        flags: LSP_DIAG_UNNECESSARY,
        line: 10,
        col: 4,
        endLine: 10,
        endCol: 9,
        code: "E0308",
        source: "rustc",
        msg: "mismatched types",
      },
      {
        kind: "file",
        hash: new Uint8Array(LSP_HASH_NONE),
        n: 0,
        path: "src/old.rs",
      },
    ];
    const buf: number[] = [];
    for (const record of records) appendLspDiagRecord(buf, record);
    expect([...lspDiagRecords(new Uint8Array(buf))]).toEqual(records);
  });

  it("round-trips query records", () => {
    const records: LspQueryRecord[] = [
      {
        kind: "location",
        flags: 0,
        hash: hash(0xcd),
        line: 5,
        col: 0,
        endLine: 5,
        endCol: 12,
        path: "src/main.rs",
      },
      {
        kind: "markup",
        format: LSP_MARKUP_MARKDOWN,
        text: "```rust\nfn main()\n```",
      },
      {
        kind: "symbol",
        symKind: 12, // Function
        flags: LSP_SYMBOL_DEPRECATED,
        depth: 1,
        line: 3,
        col: 4,
        endLine: 9,
        endCol: 1,
        name: "main",
        path: "src/main.rs",
      },
      {
        kind: "edit",
        flags: 0,
        hash: hash(0xef),
        line: 3,
        col: 7,
        endLine: 3,
        endCol: 11,
        newText: "run",
        path: "src/main.rs",
      },
    ];
    const buf: number[] = [];
    for (const record of records) appendLspQueryRecord(buf, record);
    expect([...lspQueryRecords(new Uint8Array(buf))]).toEqual(records);
  });

  it("skips unknown record kinds via record_len", () => {
    const buf: number[] = [];
    // A future record kind 0x7F with a 6-byte payload.
    buf.push(7, 0, 0, 0, 0x7f, 0x66, 0x75, 0x74, 0x75, 0x72, 0x65);
    appendLspQueryRecord(buf, {
      kind: "markup",
      format: LSP_MARKUP_PLAIN,
      text: "hi",
    });
    expect([...lspQueryRecords(new Uint8Array(buf))]).toEqual([
      { kind: "markup", format: LSP_MARKUP_PLAIN, text: "hi" },
    ]);
  });

  it("ends iteration on a malformed record", () => {
    const buf: number[] = [];
    appendLspDiagRecord(buf, {
      kind: "file",
      hash: new Uint8Array(LSP_HASH_NONE),
      n: 0,
      path: "a",
    });
    // Declared length overruns the buffer: iteration must end, not skip.
    buf.push(99, 0, 0, 0, 0x01);
    expect([...lspDiagRecords(new Uint8Array(buf))]).toHaveLength(1);
  });

  it("stops at a record whose decoder overruns the body", () => {
    // A FILE record (kind 0x01) claiming 2 body bytes but only holding the
    // kind byte plus one — its decoder overruns. It must stop iteration,
    // not skip, so a following valid record is NOT yielded (matches the
    // Rust codec).
    const buf: number[] = [];
    buf.push(2, 0, 0, 0, 0x01, 0x00); // truncated FILE
    appendLspDiagRecord(buf, {
      kind: "file",
      hash: hash(1),
      n: 0,
      path: "a",
    });
    expect([...lspDiagRecords(new Uint8Array(buf))]).toHaveLength(0);
  });

  it("rejects an oversized declared LZ4 size before allocating", () => {
    const msg: number[] = [0x61, 1, 0, 1, 0, 0, 0, 0];
    // A hostile 4 GiB declared size must be refused before allocating.
    msg.push(0xff, 0xff, 0xff, 0xff);
    msg.push(...new Array(8).fill(0));
    expect(parseLspState(new Uint8Array(msg))).toBeNull();
    expect(new LspStateMirror().applyState(new Uint8Array(msg))).toBeNull();
  });
});

describe("lsp state mirror", () => {
  it("applies snapshots as whole-state replacement", () => {
    const first: number[] = [];
    appendLspStateRecord(first, {
      kind: "server",
      serverRef: 1,
      phase: LSP_PHASE_INDEXING,
      progressPct: 10,
      caps: 0,
      epoch: 0,
      refusedEdits: 0,
      rss: 0n,
      id: "rust-analyzer",
      msg: "indexing",
    });
    const mirror = new LspStateMirror();
    expect(mirror.applyState(msgLspState(1, 1, 0, new Uint8Array(first)))).toBe(
      1,
    );
    expect(mirror.servers.size).toBe(1);
    expect(mirror.servers.get(1)?.phase).toBe(LSP_PHASE_INDEXING);

    // The next snapshot replaces, never merges.
    const second: number[] = [];
    appendLspStateRecord(second, {
      kind: "server",
      serverRef: 2,
      phase: LSP_PHASE_READY,
      progressPct: 100,
      caps: 0x3f,
      epoch: 0,
      refusedEdits: 0,
      rss: 0n,
      id: "gopls",
      msg: "",
    });
    expect(
      mirror.applyState(msgLspState(1, 2, 0, new Uint8Array(second))),
    ).toBe(2);
    expect(mirror.servers.size).toBe(1);
    expect(mirror.servers.has(2)).toBe(true);
  });
});

describe("lsp diag mirror", () => {
  it("applies per-file replacement sets", () => {
    const mirror = new LspDiagMirror();

    // FULL replay: one file, one diagnostic.
    const first: number[] = [];
    appendLspDiagRecord(first, {
      kind: "file",
      hash: hash(1),
      n: 1,
      path: "a.rs",
    });
    appendLspDiagRecord(first, {
      kind: "diag",
      severity: LSP_SEVERITY_ERROR,
      flags: 0,
      line: 1,
      col: 0,
      endLine: 1,
      endCol: 5,
      code: "E1",
      source: "t",
      msg: "boom",
    });
    expect(
      mirror.applyDiag(msgLspDiag(1, 1, LSP_DIAG_FULL, new Uint8Array(first))),
    ).toBe(1);
    expect(mirror.files.size).toBe(1);
    expect(mirror.files.get("a.rs")?.diags).toHaveLength(1);

    // Incremental: replace a.rs with an empty set (n=0 removes).
    const second: number[] = [];
    appendLspDiagRecord(second, {
      kind: "file",
      hash: hash(2),
      n: 0,
      path: "a.rs",
    });
    appendLspDiagRecord(second, {
      kind: "file",
      hash: hash(3),
      n: 1,
      path: "b.rs",
    });
    appendLspDiagRecord(second, {
      kind: "diag",
      severity: LSP_SEVERITY_WARNING,
      flags: 0,
      line: 2,
      col: 1,
      endLine: 2,
      endCol: 2,
      code: "",
      source: "t",
      msg: "hm",
    });
    expect(mirror.applyDiag(msgLspDiag(1, 2, 0, new Uint8Array(second)))).toBe(
      2,
    );
    expect(mirror.files.has("a.rs")).toBe(false);
    expect(hex(mirror.files.get("b.rs")!.hash)).toBe("03".repeat(16));

    // A later FULL drops files it does not re-list.
    expect(
      mirror.applyDiag(msgLspDiag(1, 3, LSP_DIAG_FULL, new Uint8Array(0))),
    ).toBe(3);
    expect(mirror.files.size).toBe(0);
  });
});
