[package]
name = "blit-alacritty"
version = "0.50.1"
edition.workspace = true
description = "Alacritty terminal emulator driver for blit"
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
blit-remote = { workspace = true }
alacritty_terminal = { package = "blit-alacritty-terminal", version = "=0.26.0-blit.1" }
regex = "1"
